// Code generated by ego generate from regress.ego. DO NOT EDIT.

// Package regress holds programs the compiler once got wrong, with the
// behavior a test checks.
package regress

import (
	"errors"
	"fmt"
	"io"
	"strconv"
)

// CheckKeepsErr: check doesn't overwrite an err declared before it.
//
//line regress.ego:11
func CheckKeepsErr(a, b string) (int, error) {
	x, err := strconv.Atoi(a)
	y, err2 := strconv.Atoi(b)
	if err2 != nil {
		return 0, fmt.Errorf("strconv.Atoi: %w", err2)
	}
//line regress.ego:14
	if err != nil {
		return -1, err
	}
	return x + y, nil
}

// ElseKeepsErr: neither does else.
func ElseKeepsErr(a, b string) (int, error) {
	x, err := strconv.Atoi(a)
	y, err2 := strconv.Atoi(b)
	if err2 != nil {
		y = 0
	}
//line regress.ego:24
	if err != nil {
		return -1, err
	}
	return x + y, nil
}

// ElseKeepsNamedErr: nor a named err result.
func ElseKeepsNamedErr(b string) (n int, err error) {
	y, err2 := strconv.Atoi(b)
	if err2 != nil {
		y = 7
	}
//line regress.ego:33
	n = y
	return
}

// Percent: a % in a string with nothing interpolated stays one %.
func Percent() (string, error) {
	return "", errors.New("disk 100% full")
}

// PercentF is the same with an f-string.
func PercentF() string { return "100%" }

// Sentinel: a match on an error with only sentinel arms uses errors.Is.
func Sentinel(err error) string {
	var v string
	if err == nil {
		v = "ok"
	} else if errors.Is(err, io.EOF) {
		v = "eof"
	} else {
		v = "other"
	}
	return v
}

//line regress.ego:54
type User struct{ Name string }

// OptAssign: x = u?.Name gives the zero value when u is nil.
func OptAssign(us []*User) []string {
	var out []string
	name := "unset"
	for _, u := range us {
		if u != nil {
			name = u.Name
		} else {
			name = ""
		}
//line regress.ego:62
		out = append(out, name)
	}
	return out
}

// Article is what InTx fails with.
type ArticleError interface {
	error
	isArticleError()
}

type Duplicate struct{ Slug string }

func (Duplicate) isArticleError() {}

func (e Duplicate) Error() string { return fmt.Sprintf("%v exists", e.Slug) }

// As lets pointers to Duplicate match as Duplicate.
func (e Duplicate) As(target any) bool {
	if t, ok := target.(*Duplicate); ok {
		*t = e
		return true
	}
	return false
}

type Unavailable struct{ Cause error }

func (Unavailable) isArticleError() {}

func (e Unavailable) Error() string { return fmt.Sprintf("unavailable: %v", e.Cause) }

func (e Unavailable) Unwrap() error { return e.Cause }

// As lets pointers to Unavailable match as Unavailable.
func (e Unavailable) As(target any) bool {
	if t, ok := target.(*Unavailable); ok {
		*t = e
		return true
	}
	return false
}

// inTx runs fn as a transaction would: its error comes back as an error.
//
//line regress.ego:74
func inTx(fn func() error) error { return fn() }

// PassThrough: check … as Unavailable lets a case of the set through.
func PassThrough(slug string) error {
	if err := inTx(func() error { return Duplicate{Slug: slug} }); err != nil {
		if _, ok := errors.AsType[ArticleError](err); ok {
			return err
		}
		return Unavailable{Cause: err}
	}
//line regress.ego:79
	if err := inTx(func() error { return io.EOF }); err != nil {
		if _, ok := errors.AsType[ArticleError](err); ok {
			return err
		}
		return Unavailable{Cause: err}
	}
//line regress.ego:80
	return nil
}

type Box struct{ N int }

// ShortCircuit: an if expression after && runs only when the left is true.
func ShortCircuit(p *Box) bool {
	v := p != nil
	if v {
		var v2 bool
		if p.N > 0 {
			v2 = true
		} else {
			v2 = false
		}
		v = (v2)
	}
	ok := v
//line regress.ego:88
	return ok
}

// Order: operands run left to right, around a computed one.
func Order() []string {
	var calls []string
	next := func(s string) int { calls = append(calls, s); return 1 }
	v := next("left")
	var v2 int
	if next("cond") > 0 {
		v2 = 1
	} else {
		v2 = 2
	}
	x := v + (v2)
//line regress.ego:96
	_ = x
	return calls
}

// Shadow: a match arm's names don't reach the later arms.
func Shadow(err error) string {
	ok := true
	e := "outer"
	var v string
	if e2, ok2 := errors.AsType[Duplicate](err); ok2 {
		e := e2
		v = e.Slug
	} else {
		if ok {
			v = e
		} else {
			v = "shadowed"
		}
	}
	return v
}
