// Code generated by ego generate from regress.ego. DO NOT EDIT.

// Package regress holds programs the compiler once got wrong, with the
// behavior a test checks.
package regress

import (
	"context"
	egoerrors "errors"
	egofmt "fmt"
	"io"
	"strconv"

	"github.com/effect-go/effect-go/trace"
)

// CheckKeepsErr: check doesn't overwrite an err declared before it.
//
//line regress.ego:11
func CheckKeepsErr(a, b string) (int, error) {
	x, err := strconv.Atoi(a)
	y, err2 := strconv.Atoi(b)
	if err2 != nil {
		return 0, egofmt.Errorf("strconv.Atoi: %w", err2)
	}
//line regress.ego:14
	if err != nil {
		return -1, err
	}
	return x + y, nil
}

// ElseKeepsErr: neither does else.
func ElseKeepsErr(a, b string) (int, error) {
	x, err := strconv.Atoi(a)
	y, err2 := strconv.Atoi(b)
	if err2 != nil {
		y = 0
	}
//line regress.ego:24
	if err != nil {
		return -1, err
	}
	return x + y, nil
}

// ElseKeepsNamedErr: nor a named err result.
func ElseKeepsNamedErr(b string) (n int, err error) {
	y, err2 := strconv.Atoi(b)
	if err2 != nil {
		y = 7
	}
//line regress.ego:33
	n = y
	return
}

// Percent: a % in a string with nothing interpolated stays one %.
func Percent() (string, error) {
	return "", egoerrors.New("disk 100% full")
}

// PercentF is the same with an f-string.
func PercentF() string { return "100%" }

// Sentinel: a match on an error with only sentinel arms uses errors.Is.
func Sentinel(err error) string {
	var v string
	if err == nil {
		v = "ok"
	} else if egoerrors.Is(err, io.EOF) {
		v = "eof"
	} else {
		v = "other"
	}
	return v
}

//line regress.ego:54
type User struct{ Name string }

// OptAssign: x = u?.Name gives the zero value when u is nil.
func OptAssign(us []*User) []string {
	var out []string
	name := "unset"
	for _, u := range us {
		if u != nil {
			name = u.Name
		} else {
			name = ""
		}
//line regress.ego:62
		out = append(out, name)
	}
	return out
}

// Article is what InTx fails with.
type ArticleError interface {
	error
	isArticleError()
}

type Duplicate struct{ Slug string }

func (Duplicate) isArticleError() {}

func (e Duplicate) Error() string { return egofmt.Sprintf("%v exists", e.Slug) }

// As lets pointers to Duplicate match as Duplicate.
func (e Duplicate) As(target any) bool {
	if t, ok := target.(*Duplicate); ok {
		*t = e
		return true
	}
	return false
}

type Unavailable struct{ Cause error }

func (Unavailable) isArticleError() {}

func (e Unavailable) Error() string { return egofmt.Sprintf("unavailable: %v", e.Cause) }

func (e Unavailable) Unwrap() error { return e.Cause }

// As lets pointers to Unavailable match as Unavailable.
func (e Unavailable) As(target any) bool {
	if t, ok := target.(*Unavailable); ok {
		*t = e
		return true
	}
	return false
}

// inTx runs fn as a transaction would: its error comes back as an error.
//
//line regress.ego:74
func inTx(fn func() error) error { return fn() }

// PassThrough: check … as Unavailable lets a case of the set through.
func PassThrough(slug string) error {
	if err := inTx(func() error { return Duplicate{Slug: slug} }); err != nil {
		if _, ok := egoerrors.AsType[ArticleError](err); ok {
			return err
		}
		return Unavailable{Cause: err}
	}
//line regress.ego:79
	if err := inTx(func() error { return io.EOF }); err != nil {
		if _, ok := egoerrors.AsType[ArticleError](err); ok {
			return err
		}
		return Unavailable{Cause: err}
	}
//line regress.ego:80
	return nil
}

type Box struct{ N int }

// ShortCircuit: an if expression after && runs only when the left is true.
func ShortCircuit(p *Box) bool {
	v := p != nil
	if v {
		var v2 bool
		if p.N > 0 {
			v2 = true
		} else {
			v2 = false
		}
		v = (v2)
	}
	ok := v
//line regress.ego:88
	return ok
}

// Order: operands run left to right, around a computed one.
func Order() []string {
	var calls []string
	next := func(s string) int { calls = append(calls, s); return 1 }
	v := next("left")
	var v2 int
	if next("cond") > 0 {
		v2 = 1
	} else {
		v2 = 2
	}
	x := v + (v2)
//line regress.ego:96
	_ = x
	return calls
}

// Shadow: a match arm's names don't reach the later arms.
func Shadow(err error) string {
	ok := true
	e := "outer"
	var v string
	if e2, ok2 := egoerrors.AsType[Duplicate](err); ok2 {
		e := e2
		v = e.Slug
	} else {
		if ok {
			v = e
		} else {
			v = "shadowed"
		}
	}
	return v
}

// DivOneLine panics on a line that a stack trace must report as this one.
//
//line regress.ego:111
func DivOneLine(ctx context.Context, m map[string]int) (_ int, err error) {
	ctx, span := trace.Start(ctx, "regress.DivOneLine")
	defer trace.End(span, &err)
//line regress.ego:111
	return m["a"] / len(m), nil
} // one-line

type City string

type Player struct {
	Score float64
	Home  City
}

// OptFallback: p?.Score ?? 0 is a float64, and p?.Home ?? "none" a City.
func OptFallback(p *Player) (float64, City) {
	var s float64 = 0
	if p != nil {
		s = p.Score
	}
//line regress.ego:123
	var h City = "none"
	if p != nil {
		h = p.Home
	}
//line regress.ego:124
	return s, h
}

// FStringLoop: an f-string in a for condition.
func FStringLoop(b string) int {
	n := 0
	for egofmt.Sprintf("%s%d", b, n) != "x2" {
		n++
	}
	return n
}

// Map is a generic function taking a callback.
func Map[T, R any](xs []T, f func(T) R) []R {
	var out []R
	for _, x := range xs {
		out = append(out, f(x))
	}
	return out
}

// GenericLambda: a typed lambda passed to Map gives Map its result type.
func GenericLambda(us []User) []string {
	return Map(us, func(u User) string { return u.Name })
}

// LocalNames: variables named like the packages the generated code uses.
func LocalNames(s string) (int, error) {
	errors := []string{"a"}
	fmt := len(errors)
	n, err := strconv.Atoi(s)
	if err != nil {
		if _, ok := egoerrors.AsType[ArticleError](err); ok {
			return 0, err
		}
		return 0, Unavailable{Cause: err}
	}
//line regress.ego:155
	return n + fmt, nil
}
