package lower

import (
	"bytes"
	"flag"
	"os"
	"path/filepath"
	"regexp"
	"runtime"
	"strings"
	"testing"
)

var update = flag.Bool("update", false, "rewrite the generated files in testdata")

// fixtures are the packages in internal/egotest: their generated files are
// committed, and their tests run against the generated code.
func fixtures(t *testing.T) []string {
	dirs, _ := filepath.Glob("../egotest/*")
	var out []string
	for _, d := range dirs {
		if base := filepath.Base(d); strings.HasPrefix(base, "_") || strings.HasPrefix(base, ".") {
			continue // ignored, as go ignores them
		}
		if egos, _ := filepath.Glob(filepath.Join(d, "*.ego")); len(egos) > 0 {
			out = append(out, d)
		}
	}
	if len(out) == 0 {
		t.Fatal("no fixtures")
	}
	return out
}

// Generating each fixture gives the committed Go.
func TestGolden(t *testing.T) {
	im := NewImporter()
	for _, dir := range fixtures(t) {
		t.Run(filepath.Base(dir), func(t *testing.T) {
			res, err := Generate(Config{Dir: dir, Importer: im})
			if err != nil {
				t.Fatal(err)
			}
			for _, d := range res.Diags {
				t.Error(d)
			}
			for _, out := range res.Outputs {
				if *update {
					if err := os.WriteFile(out.Go, out.Code, 0o666); err != nil {
						t.Fatal(err)
					}
					continue
				}
				want, err := os.ReadFile(out.Go)
				if err != nil {
					t.Fatalf("%v (run go test -update)", err)
				}
				if !bytes.Equal(out.Code, want) {
					t.Errorf("%s differs from the generated code (run go test -update):\n%s", out.Go, out.Code)
				}
			}
		})
	}
}

var errorRx = regexp.MustCompile(`// ERROR "([^"]*)"`)

// Each file in testdata/errors is a package whose lines marked
// // ERROR "regexp" must be reported, and nothing else.
func TestErrors(t *testing.T) {
	cases, _ := filepath.Glob("testdata/errors/*")
	im := NewImporter()
	for _, dir := range cases {
		t.Run(filepath.Base(dir), func(t *testing.T) {
			res, err := Generate(Config{Dir: dir, Importer: im})
			if err != nil {
				t.Fatal(err)
			}
			want := map[int]*regexp.Regexp{}
			egos, _ := filepath.Glob(filepath.Join(dir, "*.ego"))
			for _, f := range egos {
				src, _ := os.ReadFile(f)
				for i, line := range strings.Split(string(src), "\n") {
					if m := errorRx.FindStringSubmatch(line); m != nil {
						want[i+1] = regexp.MustCompile(m[1])
					}
				}
			}
			got := map[int]bool{}
			for _, d := range res.Diags {
				rx, ok := want[d.Pos.Line]
				if !ok || !rx.MatchString(d.Msg) {
					t.Errorf("unexpected: %v", d)
					continue
				}
				got[d.Pos.Line] = true
			}
			for line, rx := range want {
				if !got[line] {
					t.Errorf("line %d: missing error matching %q", line, rx)
				}
			}
		})
	}
}

// Plain Go is valid effect-go, and passes through unchanged: packages of
// this module and of the standard library, renamed to .ego, compile to
// themselves.
func TestPlainGoUnchanged(t *testing.T) {
	goroot := filepath.Join(runtime.GOROOT(), "src")
	for _, pkg := range []string{"../../scope", goroot + "/encoding/csv", goroot + "/text/tabwriter", goroot + "/container/list", goroot + "/net/url"} {
		t.Run(filepath.Base(pkg), func(t *testing.T) {
			dir := t.TempDir()
			os.WriteFile(filepath.Join(dir, "go.mod"), []byte("module example.com/"+filepath.Base(pkg)+"\n\ngo 1.26\n"), 0o666)
			files, _ := filepath.Glob(filepath.Join(pkg, "*.go"))
			want := map[string][]byte{}
			for _, f := range files {
				if strings.HasSuffix(f, "_test.go") {
					continue
				}
				src, _ := os.ReadFile(f)
				name := strings.TrimSuffix(filepath.Base(f), ".go") + ".ego"
				os.WriteFile(filepath.Join(dir, name), src, 0o666)
				want[GoName(name)] = src
			}
			res, err := Generate(Config{Dir: dir, NoLines: true})
			if err != nil {
				t.Fatal(err)
			}
			for _, d := range res.Diags {
				t.Error(d)
			}
			for _, out := range res.Outputs {
				header := "// Code generated by ego generate from " + strings.TrimSuffix(filepath.Base(out.Go), "_ego.go") + ".ego. DO NOT EDIT.\n\n"
				if got, w := string(out.Code), header+string(want[filepath.Base(out.Go)]); got != w {
					t.Errorf("%s changed:\n%s", filepath.Base(out.Go), got)
				}
			}
		})
	}
}
