// Code generated by ego generate from users.ego. DO NOT EDIT.

// Package users is the user service of ../users.go, written in the
// effect-go dialect. ego generate compiles it to users_ego.go.
package users

import (
	"context"
	"errors"
	"fmt"
	"net/http"
	"time"

	"github.com/effect-go/effect-go/trace"
)

//line users.ego:11
type UserID string

type User struct {
	ID             UserID
	Name           string
	SuspendedUntil time.Time
}

type Repo interface {
	Find(ctx context.Context, id UserID) (u User, found bool, err error)
}

// UserError is the error set NotFound | Suspended | Storage.
type UserError interface {
	error
	isUserError()
}

type NotFound struct{ ID UserID }

func (NotFound) isUserError() {}

func (e NotFound) Error() string { return fmt.Sprintf("not found (ID %v)", e.ID) }

// As lets pointers to NotFound match as NotFound.
func (e NotFound) As(target any) bool {
	if t, ok := target.(*NotFound); ok {
		*t = e
		return true
	}
	return false
}

type Suspended struct{ Until time.Time }

func (Suspended) isUserError() {}

func (e Suspended) Error() string { return fmt.Sprintf("suspended (Until %v)", e.Until) }

// As lets pointers to Suspended match as Suspended.
func (e Suspended) As(target any) bool {
	if t, ok := target.(*Suspended); ok {
		*t = e
		return true
	}
	return false
}

type Storage struct{ Cause error }

func (Storage) isUserError() {}

func (e Storage) Error() string { return fmt.Sprintf("storage: %v", e.Cause) }

func (e Storage) Unwrap() error { return e.Cause }

// As lets pointers to Storage match as Storage.
func (e Storage) As(target any) bool {
	if t, ok := target.(*Storage); ok {
		*t = e
		return true
	}
	return false
}

//line users.ego:29
type Service struct {
	Repo Repo
	Now  func() time.Time
}

func (s *Service) Get(ctx context.Context, id UserID) (_ User, err error) {
	ctx, span := trace.Start(ctx, "users.Service.Get")
	defer trace.End(span, &err)
//line users.ego:35
	u, ok, err := s.Repo.Find(ctx, id)
	if err != nil {
		return User{}, Storage{Cause: err}
	}
//line users.ego:36
	if !ok {
		return User{}, NotFound{ID: id}
	}
	if u.SuspendedUntil.After(s.Now()) {
		return User{}, Suspended{Until: u.SuspendedUntil}
	}
	return u, nil
}

type Handler struct{ Users *Service }

func (h *Handler) GetUser(w http.ResponseWriter, r *http.Request) {
	u, err := h.Users.Get(r.Context(), UserID(r.PathValue("id")))
	if err == nil {
		fmt.Fprintf(w, "%s\n", u.Name)
	} else if e, ok := errors.AsType[NotFound](err); ok {
//line users.ego:51
		http.Error(w, fmt.Sprintf("no user %s", e.ID), http.StatusNotFound)
	} else if e, ok := errors.AsType[Suspended](err); ok {
//line users.ego:52
		http.Error(w, fmt.Sprintf("suspended until %s", e.Until.Format(time.DateOnly)), http.StatusForbidden)
	} else if _, ok := errors.AsType[Storage](err); ok {
//line users.ego:53
		http.Error(w, "try again later", http.StatusServiceUnavailable)
	} else {
		panic(err)
	}
}
