// Code generated by ego generate. DO NOT EDIT.

//go:build !egolayers

package app

import (
	"context"
	"fmt"

	"github.com/effect-go/effect-go/scope"
)

// BuildApp builds the app for production.
func BuildApp(ctx context.Context, s *scope.Scope, cfg Config) (*App, error) {
	db, err := NewDB(ctx, cfg)
	if err != nil {
		return nil, fmt.Errorf("NewDB: %w", err)
	}
	s.Defer(func(context.Context) error { return db.Close() })
	pgRepo := NewPgRepo(db)
	cache, cleanup, err := NewCache(cfg)
	if err != nil {
		return nil, fmt.Errorf("NewCache: %w", err)
	}
	s.Defer(func(context.Context) error { cleanup(); return nil })
	service := NewService(pgRepo, cache)
	app, err := NewApp(service)
	if err != nil {
		return nil, fmt.Errorf("NewApp: %w", err)
	}
	return app, nil
}

// BuildTestApp builds the app with an in-memory repository.
func BuildTestApp(ctx context.Context, s *scope.Scope, cfg Config) (*App, error) {
	memRepo := NewMemRepo()
	cache, cleanup, err := NewCache(cfg)
	if err != nil {
		return nil, fmt.Errorf("NewCache: %w", err)
	}
	s.Defer(func(context.Context) error { cleanup(); return nil })
	service := NewService(memRepo, cache)
	app, err := NewApp(service)
	if err != nil {
		return nil, fmt.Errorf("NewApp: %w", err)
	}
	return app, nil
}
