// Code generated by ego generate from consumer.ego. DO NOT EDIT.

// Package consumer calls another .ego package's effect functions.
package consumer

import (
	"context"
	"fmt"

	"github.com/effect-go/effect-go/internal/egotest/multi"
	"github.com/effect-go/effect-go/trace"
)

//line consumer.ego:6
func Words(ctx context.Context, text string) (_ int, err error) {
	ctx, span := trace.Start(ctx, "consumer.Words")
	defer trace.End(span, &err)
//line consumer.ego:7
	s := multi.NewStore[string, int]()
	n, err := multi.Count(ctx, s, text)
	if err != nil {
		return 0, fmt.Errorf("count words: %w", err)
	}
//line consumer.ego:9
	return n, nil
}
