// Code generated by ego generate from external_test.ego. DO NOT EDIT.

package status_test

import (
	"errors"
	"fmt"
	"net/http"
	"testing"

	"github.com/effect-go/effect-go/internal/egotest/status"
)

// An external test in effect-go: it matches the package's error set.
//
//line external_test.ego:10
func TestExternal(t *testing.T) {
	for amount, want := range map[int]string{0: "declined: nothing to charge", 500: "gateway failed: timeout", 5: "ok"} {
		_, err := status.Pay(amount)
		var got string
		if err == nil {
			got = "ok"
		} else if d, ok := errors.AsType[status.Declined](err); ok {
			got = fmt.Sprintf("declined: %s", d.Reason)
		} else if g, ok := errors.AsType[status.Gateway](err); ok {
			got = fmt.Sprintf("gateway failed: %v", g.Cause)
		} else if _, ok := errors.AsType[status.Expired](err); ok {
			got = "expired"
		} else {
			panic(err)
		}
//line external_test.ego:20
		if got != want {
			t.Errorf("Pay(%d): %s, want %s", amount, got, want)
		}
	}
}

// The external test and the package share the standard library's types.
func TestSharedTypes(t *testing.T) {
	var h http.Handler = status.Handler()
	if h == nil {
		t.Fatal("no handler")
	}
}
