// Code generated by ego generate from status.ego. DO NOT EDIT.

package status

import (
	"errors"
	"fmt"
	"net/http"
)

// PayError is the error set Declined | Expired | Gateway.
//
//line status.ego:8
type PayError interface {
	error
	isPayError()
}

type Declined struct{ Reason string }

func (Declined) isPayError() {}

func (e Declined) Error() string { return fmt.Sprintf("declined: %v", e.Reason) }

type Expired struct{}

func (Expired) isPayError() {}

func (e Expired) Error() string { return "expired" }

type Gateway struct{ Cause error }

func (Gateway) isPayError() {}

func (e Gateway) Error() string { return fmt.Sprintf("gateway: %v", e.Cause) }

func (e Gateway) Unwrap() error { return e.Cause }

//line status.ego:14
func Code(err error) int {
	var code int
	if err == nil {
		code = http.StatusOK
	} else if _, ok := errors.AsType[Declined](err); ok {
		code = http.StatusPaymentRequired
	} else if _, ok := errors.AsType[Expired](err); ok {
		code = http.StatusGone
	} else if _, ok := errors.AsType[Gateway](err); ok {
		code = http.StatusBadGateway
	} else {
		panic(err)
	}
//line status.ego:21
	return code
}

func Describe(err error) string {
	var v string
	if err == nil {
		v = "ok"
	} else if d, ok := errors.AsType[Declined](err); ok {
		v = d.Reason
	} else {
		v = "failed: " + err.Error()
	}
	return v
}

//line status.ego:32
func Charge(amount int) (string, error) {
	if amount <= 0 {
		return "", Declined{Reason: "nothing to charge"}
	}
	if amount > 100 {
		return "", Gateway{Cause: errors.New("timeout")}
	}
	return "ok", nil
}

// Pay passes Charge's errors on unchanged: they are the same set.
func Pay(amount int) (string, error) {
	r, err := Charge(amount)
	if err != nil {
		return "", err
	}
//line status.ego:45
	return r, nil
}
