// Code generated by ego generate from status.ego. DO NOT EDIT.

package status

import (
	"errors"
	"fmt"
	"math"
	"net/http"
	"runtime"
	"strconv"
)

// PayError is the error set Declined | Expired | Gateway.
//
//line status.ego:11
type PayError interface {
	error
	isPayError()
}

// Declined means the bank refused the payment.
type Declined struct{ Reason string }

func (Declined) isPayError() {}

func (e Declined) Error() string { return fmt.Sprintf("declined: %v", e.Reason) }

// As lets pointers to Declined match as Declined.
func (e Declined) As(target any) bool {
	if t, ok := target.(*Declined); ok {
		*t = e
		return true
	}
	return false
}

type Expired struct{} // the card's date has passed

func (Expired) isPayError() {}

func (e Expired) Error() string { return "expired" }

// As lets pointers to Expired match as Expired.
func (e Expired) As(target any) bool {
	if t, ok := target.(*Expired); ok {
		*t = e
		return true
	}
	return false
}

type Gateway struct{ Cause error }

func (Gateway) isPayError() {}

func (e Gateway) Error() string { return fmt.Sprintf("gateway: %v", e.Cause) }

func (e Gateway) Unwrap() error { return e.Cause }

// As lets pointers to Gateway match as Gateway.
func (e Gateway) As(target any) bool {
	if t, ok := target.(*Gateway); ok {
		*t = e
		return true
	}
	return false
}

// Where returns the line it runs on, which the generated Go must report as
// this file's, though the error set above takes more lines in Go.
//
//line status.ego:20
func Where() int {
	_, _, line, _ := runtime.Caller(0) // where
	return line
}

// Code maps a payment's result to an HTTP status. err is declared as a
// PayError, so the match needs no _ arm.
func Code(err error) int {
	var code int
	if err == nil {
		code = http.StatusOK
	} else if _, ok := errors.AsType[Declined](err); ok {
		code = http.StatusPaymentRequired
	} else if _, ok := errors.AsType[Expired](err); ok {
		code = http.StatusGone
	} else if _, ok := errors.AsType[Gateway](err); ok {
		code = http.StatusBadGateway
	} else {
		panic(err)
	}
//line status.ego:34
	return code
}

func Describe(err error) string {
	var v string
	if err == nil {
		v = "ok"
	} else if d, ok := errors.AsType[Declined](err); ok {
		v = d.Reason
	} else {
		v = "failed: " + err.Error()
	}
	return v
}

//line status.ego:45
func Charge(amount int) (string, error) {
	if amount <= 0 {
		return "", Declined{Reason: "nothing to charge"}
	}
	if amount > 100 {
		return "", Gateway{Cause: errors.New("timeout")}
	}
	return "ok", nil
}

// Amount parses an amount. A bad one is Declined, with its own message.
func Amount(s string) (int, error) {
	n, err := strconv.Atoi(s)
	if err != nil {
		return 0, Declined{Reason: fmt.Sprintf("bad amount %q", s)}
	}
//line status.ego:58
	return n, nil
}

// Remote keeps the cause: Gateway's error field gets it.
func Remote(s string) (int, error) {
	n, err := strconv.Atoi(s)
	if err != nil {
		return 0, Gateway{Cause: err}
	}
//line status.ego:64
	return n, nil
}

// Pay passes Charge's errors on unchanged: they are the same set.
func Pay(amount int) (string, error) {
	r, err := Charge(amount)
	if err != nil {
		return "", err
	}
//line status.ego:70
	return r, nil
}

// Settle recovers from a declined charge and returns the other errors,
// labelled.
func Settle(amount int) (string, error) {
	r, err := Charge(amount)
	if err != nil {
		if d, ok := errors.AsType[Declined](err); ok {
			r = fmt.Sprintf("skipped: %s", d.Reason)
		} else {
			return "", fmt.Errorf("settle %v: %w", amount, err)
		}
	}
//line status.ego:77
	return r, nil
}

// State handles every case of the set, so it needs no check.
func State(amount int) (s string) {
	v, err := Charge(amount)
	if err != nil {
		if _, ok := errors.AsType[Declined](err); ok {
			v = "declined"
		} else if _, ok := errors.AsType[Expired](err); ok {
			v = "retry later"
		} else if _, ok := errors.AsType[Gateway](err); ok {
			v = "retry later"
		} else {
			panic(err)
		}
	}
	s = v
//line status.ego:83
	return s
}

// Clamp saturates numbers out of range: strconv.ErrRange is found inside
// the *strconv.NumError that wraps it.
func Clamp(s string) (int, error) {
	n, err := strconv.Atoi(s)
	if err != nil {
		if errors.Is(err, strconv.ErrRange) {
			n = math.MaxInt
		} else {
			return 0, fmt.Errorf("strconv.Atoi: %w", err)
		}
	}
//line status.ego:90
	return n, nil
}

// Parse passes strconv's error on as it is: an empty label adds nothing.
func Parse(s string) (int, error) {
	n, err := strconv.Atoi(s)
	if err != nil {
		return 0, err
	}
//line status.ego:96
	return n, nil
}

// Both reads two numbers. A later err := of its own doesn't clash with the
// error variable of check.
func Both(a, b string) (int, error) {
	x, err2 := strconv.Atoi(a)
	if err2 != nil {
		return 0, err2
	}
//line status.ego:103
	y, err3 := strconv.Atoi(b)
	if err3 != nil {
		return 0, err3
	}
//line status.ego:104
	err := error(nil)
	if x+y < 0 {
		err = errors.New("negative")
	}
	return x + y, err
}

// Handler returns a net/http type, for the external test.
func Handler() http.Handler { return http.NotFoundHandler() }
