// Code generated by ego generate from status.ego. DO NOT EDIT.

package status

import (
	"errors"
	"fmt"
	"math"
	"net/http"
	"strconv"
)

// PayError is the error set Declined | Expired | Gateway.
//
//line status.ego:10
type PayError interface {
	error
	isPayError()
}

type Declined struct{ Reason string }

func (Declined) isPayError() {}

func (e Declined) Error() string { return fmt.Sprintf("declined: %v", e.Reason) }

type Expired struct{}

func (Expired) isPayError() {}

func (e Expired) Error() string { return "expired" }

type Gateway struct{ Cause error }

func (Gateway) isPayError() {}

func (e Gateway) Error() string { return fmt.Sprintf("gateway: %v", e.Cause) }

func (e Gateway) Unwrap() error { return e.Cause }

//line status.ego:16
func Code(err error) int {
	var code int
	if err == nil {
		code = http.StatusOK
	} else if _, ok := errors.AsType[Declined](err); ok {
		code = http.StatusPaymentRequired
	} else if _, ok := errors.AsType[Expired](err); ok {
		code = http.StatusGone
	} else if _, ok := errors.AsType[Gateway](err); ok {
		code = http.StatusBadGateway
	} else {
		panic(err)
	}
//line status.ego:23
	return code
}

func Describe(err error) string {
	var v string
	if err == nil {
		v = "ok"
	} else if d, ok := errors.AsType[Declined](err); ok {
		v = d.Reason
	} else {
		v = "failed: " + err.Error()
	}
	return v
}

//line status.ego:34
func Charge(amount int) (string, error) {
	if amount <= 0 {
		return "", Declined{Reason: "nothing to charge"}
	}
	if amount > 100 {
		return "", Gateway{Cause: errors.New("timeout")}
	}
	return "ok", nil
}

// Amount parses an amount. A bad one is Declined, with its own message.
func Amount(s string) (int, error) {
	n, err := strconv.Atoi(s)
	if err != nil {
		return 0, Declined{Reason: fmt.Sprintf("bad amount %q", s)}
	}
//line status.ego:47
	return n, nil
}

// Remote keeps the cause: Gateway's error field gets it.
func Remote(s string) (int, error) {
	n, err := strconv.Atoi(s)
	if err != nil {
		return 0, Gateway{Cause: err}
	}
//line status.ego:53
	return n, nil
}

// Pay passes Charge's errors on unchanged: they are the same set.
func Pay(amount int) (string, error) {
	r, err := Charge(amount)
	if err != nil {
		return "", err
	}
//line status.ego:59
	return r, nil
}

// Settle recovers from a declined charge and returns the other errors,
// labelled.
func Settle(amount int) (string, error) {
	r, err := Charge(amount)
	if err != nil {
		if d, ok := errors.AsType[Declined](err); ok {
			r = fmt.Sprintf("skipped: %s", d.Reason)
		} else {
			return "", fmt.Errorf("settle %v: %w", amount, err)
		}
	}
//line status.ego:66
	return r, nil
}

// State handles every case of the set, so it needs no check.
func State(amount int) (s string) {
	v, err := Charge(amount)
	if err != nil {
		if _, ok := errors.AsType[Declined](err); ok {
			v = "declined"
		} else if _, ok := errors.AsType[Expired](err); ok {
			v = "retry later"
		} else if _, ok := errors.AsType[Gateway](err); ok {
			v = "retry later"
		} else {
			panic(err)
		}
	}
	s = v
//line status.ego:72
	return s
}

// Clamp saturates numbers out of range: strconv.ErrRange is found inside
// the *strconv.NumError that wraps it.
func Clamp(s string) (int, error) {
	n, err := strconv.Atoi(s)
	if err != nil {
		if errors.Is(err, strconv.ErrRange) {
			n = math.MaxInt
		} else {
			return 0, fmt.Errorf("strconv.Atoi: %w", err)
		}
	}
//line status.ego:79
	return n, nil
}
