// Code generated by ego generate from dashboard.ego. DO NOT EDIT.

package dashboard

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/effect-go/effect-go/schedule"

	"github.com/effect-go/effect-go/scope"
	"github.com/effect-go/effect-go/trace"
)

//line dashboard.ego:10
var recsRetry = schedule.Max(schedule.Exponential(100*time.Millisecond), schedule.Recurs(3)).
	Jittered().
	While(func(err error) bool { return !errors.Is(err, ErrRejected) })

// LoadEgo builds the page, written in the effect-go dialect.
func LoadEgo(ctx context.Context, d Deps, id string) (_ Page, err error) {
	ctx, span := trace.Start(ctx, "dashboard.LoadEgo")
	defer trace.End(span, &err)
//line dashboard.ego:16
	return scope.Timeout(ctx, 2*time.Second, func(ctx context.Context) (Page, error) { return loadEgo(ctx, d, id) })
}

func loadEgo(ctx context.Context, d Deps, id string) (_ Page, err error) {
	ctx, span := trace.Start(ctx, "dashboard.loadEgo")
	defer trace.End(span, &err)
//line dashboard.ego:20
	user, orders, recs, err := scope.All3(ctx,
		func(ctx context.Context) (User, error) { return d.Users.Get(ctx, id) },
		func(ctx context.Context) ([]Order, error) { return d.Orders.ForUser(ctx, id) },
		func(ctx context.Context) ([]Product, error) {
			return schedule.Retry(ctx, recsRetry, func(ctx context.Context) ([]Product, error) { return d.Recs.For(ctx, id) })
		},
	)
	if err != nil {
		return Page{}, err
	}
//line dashboard.ego:21
	banner, err := scope.Race(ctx,
		func(ctx context.Context) (Image, error) { return d.CDN.Primary(ctx, user.Banner) },
		func(ctx context.Context) (Image, error) { return d.CDN.Mirror(ctx, user.Banner) },
	)
	if err != nil {
		return Page{}, fmt.Errorf("banner: %w", err)
	}
//line dashboard.ego:22
	return Page{User: user, Orders: orders, Recs: recs, Banner: banner}, nil
}
