// Code generated by ego generate from jsonrpc.ego. DO NOT EDIT.

package lsp

import (
	"bufio"
	"encoding/json"
	"fmt"
	"io"
	"net/textproto"
	"strconv"
	"strings"
	"sync"
)

// A message is a JSON-RPC 2.0 request, notification or response.
//
//line jsonrpc.ego:14
type message struct {
	JSONRPC string          `json:"jsonrpc"`
	ID      json.RawMessage `json:"id,omitempty"`
	Method  string          `json:"method,omitempty"`
	Params  json.RawMessage `json:"params,omitempty"`
	Result  json.RawMessage `json:"result,omitempty"`
	Error   json.RawMessage `json:"error,omitempty"`
}

func (m *message) isRequest() bool  { return m.Method != "" && len(m.ID) > 0 }
func (m *message) isResponse() bool { return m.Method == "" && len(m.ID) > 0 }

// conn reads and writes LSP messages framed by Content-Length headers.
type conn struct {
	r    *bufio.Reader
	mu   sync.Mutex
	w    io.Writer
	name string    // for the log
	log  io.Writer // may be nil
}

func newConn(r io.Reader, w io.Writer) *conn { return &conn{r: bufio.NewReader(r), w: w} }

func (c *conn) read() (*message, error) {
	tp := textproto.NewReader(c.r)
	h, err := tp.ReadMIMEHeader()
	if err != nil {
		return nil, err
	}
//line jsonrpc.ego:41
	n, err := strconv.Atoi(strings.TrimSpace(h.Get("Content-Length")))
	if err != nil {
		return nil, fmt.Errorf("bad Content-Length: %w", err)
	}
//line jsonrpc.ego:42
	body := make([]byte, n)
	if _, err := io.ReadFull(c.r, body); err != nil {
		return nil, err
	}
//line jsonrpc.ego:44
	m := &message{}
	if err := json.Unmarshal(body, m); err != nil {
		return nil, err
	}
//line jsonrpc.ego:46
	if c.log != nil {
		fmt.Fprintf(c.log, "<- %s %s\n", c.name, truncate(body))
	}
	return m, nil
}

func (c *conn) write(m *message) error {
	m.JSONRPC = "2.0"
	body, err := json.Marshal(m)
	if err != nil {
		return err
	}
//line jsonrpc.ego:55
	c.mu.Lock()
	defer c.mu.Unlock()
	if c.log != nil {
		fmt.Fprintf(c.log, "-> %s %s\n", c.name, truncate(body))
	}
	if _, err := fmt.Fprintf(c.w, "Content-Length: %d\r\n\r\n", len(body)); err != nil {
		return err
	}
//line jsonrpc.ego:61
	if _, err := c.w.Write(body); err != nil {
		return err
	}
//line jsonrpc.ego:62
	return nil
}

func (c *conn) notify(method string, params any) error {
	p, err := json.Marshal(params)
	if err != nil {
		return err
	}
//line jsonrpc.ego:67
	return c.write(&message{Method: method, Params: p})
}

func (c *conn) reply(id json.RawMessage, result any) error {
	r, err := json.Marshal(result)
	if err != nil {
		return err
	}
//line jsonrpc.ego:72
	return c.write(&message{ID: id, Result: r})
}

func (c *conn) replyError(id json.RawMessage, code int, msg string) error {
	e, _ := json.Marshal(map[string]any{"code": code, "message": msg})
	return c.write(&message{ID: id, Error: e})
}

func truncate(b []byte) string {
	if len(b) > 400 {
		return string(b[:400]) + "…"
	}
	return string(b)
}
