// Code generated by ego generate from users.ego. DO NOT EDIT.

package users

import (
	"context"
	"errors"
	"fmt"
	"net/http"
	"time"

	"github.com/effect-go/effect-go/trace"
)

//line users.ego:9
type UserID string

type User struct {
	ID             UserID
	Name           string
	SuspendedUntil time.Time
}

type Repo interface {
	Find(ctx context.Context, id UserID) (user User, found bool, err error)
}

// UserError is the error set NotFound | Suspended | Storage.
type UserError interface {
	error
	isUserError()
}

type NotFound struct{ ID UserID }

func (NotFound) isUserError() {}

func (e NotFound) Error() string { return fmt.Sprintf("no user %v", e.ID) }

type Suspended struct{ Until time.Time }

func (Suspended) isUserError() {}

func (e Suspended) Error() string { return fmt.Sprintf("suspended until %v", e.Until) }

type Storage struct{ Cause error }

func (Storage) isUserError() {}

func (e Storage) Error() string { return fmt.Sprintf("storage: %v", e.Cause) }

func (e Storage) Unwrap() error { return e.Cause }

//line users.ego:27
type Service struct {
	Repo Repo
	Now  func() time.Time
}

func (s *Service) Get(ctx context.Context, id UserID) (_ User, err error) {
	ctx, span := trace.Start(ctx, "Service.Get")
	defer trace.End(span, &err)
//line users.ego:33
	u, found, err := s.Repo.Find(ctx, id)
	if err != nil {
		return User{}, Storage{Cause: err}
	}
//line users.ego:34
	if !found {
		return User{}, NotFound{ID: id}
	}
	if u.SuspendedUntil.After(s.Now()) {
		return User{}, Suspended{Until: u.SuspendedUntil}
	}
	return u, nil
}

type Handler struct{ Users *Service }

func (h *Handler) GetUser(w http.ResponseWriter, r *http.Request) {
	u, err := h.Users.Get(r.Context(), UserID(r.PathValue("id")))
	if err == nil {
		fmt.Fprintln(w, u.Name)
	} else if e, ok := errors.AsType[NotFound](err); ok {
//line users.ego:49
		http.Error(w, fmt.Sprintf("no user %s", e.ID), http.StatusNotFound)
	} else if e, ok := errors.AsType[Suspended](err); ok {

//line users.ego:51
		until := e.Until.Format("2006-01-02")
		http.Error(w, fmt.Sprintf("suspended until %s", until), http.StatusForbidden)

	} else if _, ok := errors.AsType[Storage](err); ok {
//line users.ego:54
		http.Error(w, "try again later", http.StatusServiceUnavailable)
	} else {
		panic(err)
	}
}
