// Code generated by ego generate from users.ego. DO NOT EDIT.

package users

import (
	"context"
	"errors"
	"fmt"
	"net/http"
	"time"

	"github.com/effect-go/effect-go/trace"
)

//line users.ego:9
type UserID string

type User struct {
	ID             UserID
	Name           string
	SuspendedUntil time.Time
}

// Repo looks users up in storage.
type Repo interface {
	Find(ctx context.Context, id UserID) (user User, found bool, err error)
}

// UserError is every way Service.Get can fail.
type UserError interface {
	error
	isUserError()
}

type NotFound struct{ ID UserID }

func (NotFound) isUserError() {}

func (e NotFound) Error() string { return fmt.Sprintf("no user %v", e.ID) }

type Suspended struct{ Until time.Time }

func (Suspended) isUserError() {}

func (e Suspended) Error() string { return fmt.Sprintf("suspended (Until %v)", e.Until) }

type Storage struct{ Cause error }

func (Storage) isUserError() {}

func (e Storage) Error() string { return fmt.Sprintf("storage: %v", e.Cause) }

func (e Storage) Unwrap() error { return e.Cause }

//line users.ego:29
type Service struct {
	Repo Repo
	Now  func() time.Time
}

// Get returns the user id, unless it is missing or suspended.
func (s *Service) Get(ctx context.Context, id UserID) (_ User, err error) {
	ctx, span := trace.Start(ctx, "users.Service.Get")
	defer trace.End(span, &err)
//line users.ego:36
	u, found, err := s.Repo.Find(ctx, id)
	if err != nil {
		return User{}, Storage{Cause: err}
	}
//line users.ego:37
	if !found {
		return User{}, NotFound{ID: id}
	}
	if u.SuspendedUntil.After(s.Now()) {
		return User{}, Suspended{Until: u.SuspendedUntil}
	}
	return u, nil
}

type Handler struct{ Users *Service }

// GetUser serves GET /users/{id}.
func (h *Handler) GetUser(w http.ResponseWriter, r *http.Request) {
	id := UserID(r.PathValue("id"))
	u, err := h.Users.Get(r.Context(), id)
	if err == nil {
		fmt.Fprintln(w, u.Name)
	} else if e, ok := errors.AsType[NotFound](err); ok {
//line users.ego:54
		http.Error(w, fmt.Sprintf("no user %s", e.ID), http.StatusNotFound)
	} else if e, ok := errors.AsType[Suspended](err); ok {
//line users.ego:55
		http.Error(w, fmt.Sprintf("suspended until %s", e.Until.Format("2006-01-02")), http.StatusForbidden)
	} else if _, ok := errors.AsType[Storage](err); ok {
//line users.ego:56
		http.Error(w, "try again later", http.StatusServiceUnavailable)
	} else {
		panic(err)
	}
}
