// Package layers generates the wiring for layer.Build injectors: plain Go
// that calls each provider once, in dependency order, and registers
// finalizers on the scope.
package layers

import (
	"bytes"
	"fmt"
	"github.com/effect-go/effect-go/internal/typeutil"
	"go/ast"
	"go/format"
	"go/token"
	"go/types"
	"os"
	"path"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
	"unicode"

	"golang.org/x/tools/go/packages"
)

const (
	layerPath = "github.com/effect-go/effect-go/layer"
	scopePath = "github.com/effect-go/effect-go/scope"
	// Tag is the build tag of injector files.
	Tag = "egolayers"
	// FileName is the generated file.
	FileName = "layers_ego.go"
)

// A Diagnostic is an error in an injector.
type Diagnostic struct {
	Pos token.Position
	Msg string
}

func (d Diagnostic) String() string { return fmt.Sprintf("%v: %s", d.Pos, d.Msg) }

// Result is the generated file, or the reasons there is none.
type Result struct {
	Path  string
	Code  []byte
	Diags []Diagnostic
}

// HasInjectors reports whether dir has injector files.
func HasInjectors(dir string) bool {
	entries, _ := os.ReadDir(dir)
	for _, e := range entries {
		if strings.HasSuffix(e.Name(), ".go") && isInjectorFile(filepath.Join(dir, e.Name())) {
			return true
		}
	}
	return false
}

func isInjectorFile(path string) bool {
	data, err := os.ReadFile(path)
	if err != nil {
		return false
	}
	for line := range strings.SplitSeq(string(data), "\n") {
		line = strings.TrimSpace(line)
		if strings.HasPrefix(line, "package ") {
			return false
		}
		if strings.HasPrefix(line, "//go:build ") && strings.TrimSpace(strings.TrimPrefix(line, "//go:build ")) == Tag {
			return true
		}
	}
	return false
}

// Generate writes nothing: it returns the wiring for the injectors in dir,
// or nil if there are none.
func Generate(dir string) (*Result, error) {
	if !HasInjectors(dir) {
		return nil, nil
	}
	cfg := &packages.Config{
		Mode:       packages.NeedName | packages.NeedFiles | packages.NeedSyntax | packages.NeedTypes | packages.NeedTypesInfo | packages.NeedImports,
		Dir:        dir,
		BuildFlags: []string{"-tags=" + Tag},
	}
	pkgs, err := packages.Load(cfg, ".")
	if err != nil {
		return nil, err
	}
	if len(pkgs) != 1 {
		return nil, fmt.Errorf("%s: expected one package", dir)
	}
	pkg := pkgs[0]
	res := &Result{Path: filepath.Join(dir, FileName)}
	if len(pkg.Errors) > 0 {
		for _, e := range pkg.Errors {
			res.Diags = append(res.Diags, Diagnostic{Pos: parsePos(e.Pos), Msg: e.Msg})
		}
		return res, nil
	}
	g := &gen{pkg: pkg, imports: map[string]string{}}
	var bodies []string
	var injectorFiles []*ast.File
	for _, f := range pkg.Syntax {
		if !isInjectorFile(pkg.Fset.File(f.Pos()).Name()) {
			continue
		}
		injectorFiles = append(injectorFiles, f)
		for _, d := range f.Decls {
			fd, ok := d.(*ast.FuncDecl)
			if !ok || fd.Body == nil {
				continue
			}
			args, ok := g.buildCall(fd)
			if !ok {
				continue
			}
			g.file = f
			if body, ok := g.injector(fd, args); ok {
				bodies = append(bodies, body)
			}
		}
	}
	res.Diags = g.diags
	if len(res.Diags) > 0 {
		return res, nil
	}
	var b bytes.Buffer
	b.WriteString("// Code generated by ego generate. DO NOT EDIT.\n\n//go:build !" + Tag + "\n\npackage " + pkg.Name + "\n\n")
	if len(g.imports) > 0 {
		b.WriteString("import (\n")
		var paths []string
		for p := range g.imports {
			paths = append(paths, p)
		}
		sort.Strings(paths)
		blank := false
		for _, p := range paths {
			if std := !strings.Contains(strings.SplitN(p, "/", 2)[0], "."); !std && !blank {
				b.WriteString("\n")
				blank = true
			}
			if g.imports[p] != path.Base(p) {
				b.WriteString(g.imports[p] + " ")
			}
			b.WriteString(strconv.Quote(p) + "\n")
		}
		b.WriteString(")\n\n")
	}
	b.WriteString(strings.Join(bodies, "\n"))
	code, err := format.Source(b.Bytes())
	if err != nil {
		return nil, fmt.Errorf("internal error: %v\n%s", err, b.Bytes())
	}
	res.Code = code
	return res, nil
}

func parsePos(s string) token.Position {
	parts := strings.Split(s, ":")
	p := token.Position{Filename: parts[0]}
	if len(parts) > 1 {
		p.Line, _ = strconv.Atoi(parts[1])
	}
	if len(parts) > 2 {
		p.Column, _ = strconv.Atoi(parts[2])
	}
	return p
}

type gen struct {
	pkg     *packages.Package
	file    *ast.File
	imports map[string]string // path -> name
	diags   []Diagnostic
}

func (g *gen) errorf(pos token.Pos, format string, args ...any) {
	g.diags = append(g.diags, Diagnostic{Pos: g.pkg.Fset.Position(pos), Msg: fmt.Sprintf(format, args...)})
}

// buildCall returns the arguments of panic(layer.Build(...)) if fd's body is
// just that.
func (g *gen) buildCall(fd *ast.FuncDecl) ([]ast.Expr, bool) {
	if len(fd.Body.List) != 1 {
		return nil, false
	}
	es, ok := fd.Body.List[0].(*ast.ExprStmt)
	if !ok {
		return nil, false
	}
	p, ok := es.X.(*ast.CallExpr)
	if !ok || len(p.Args) != 1 {
		return nil, false
	}
	if id, ok := p.Fun.(*ast.Ident); !ok || id.Name != "panic" {
		return nil, false
	}
	c, ok := p.Args[0].(*ast.CallExpr)
	if !ok || !g.isLayerFunc(c.Fun, "Build") {
		return nil, false
	}
	return c.Args, true
}

func (g *gen) isLayerFunc(x ast.Expr, name string) bool {
	var id *ast.Ident
	switch x := x.(type) {
	case *ast.SelectorExpr:
		id = x.Sel
	case *ast.Ident:
		id = x
	default:
		return false
	}
	f, ok := g.pkg.TypesInfo.Uses[id].(*types.Func)
	return ok && f.Pkg() != nil && f.Pkg().Path() == layerPath && f.Name() == name
}

// A provider is a constructor in the graph.
type provider struct {
	expr    ast.Expr // as written
	sig     *types.Signature
	out     types.Type
	hasErr  bool
	cleanup string // "", "func()", "func() error", "func(ctx) error"
	close   bool   // layer.Close: call out.Close when the scope closes
	direct  bool   // passed to Build itself, not through a Set
	used    bool
}

func (p *provider) name() string { return types.ExprString(p.expr) }

// providers collects the providers in args.
func (g *gen) providers(args []ast.Expr, direct bool, seen map[types.Object]bool) []*provider {
	var out []*provider
	for _, a := range args {
		a = ast.Unparen(a)
		if c, ok := a.(*ast.CallExpr); ok && g.isLayerFunc(c.Fun, "Close") && len(c.Args) == 1 {
			for _, p := range g.providers(c.Args, direct, seen) {
				p.close = true
				if !hasClose(p.out) {
					g.errorf(c.Pos(), "layer.Close: %s has no Close method", g.typeString(p.out))
				}
				out = append(out, p)
			}
			continue
		}
		if c, ok := a.(*ast.CallExpr); ok && g.isLayerFunc(c.Fun, "Set") {
			out = append(out, g.providers(c.Args, false, seen)...)
			continue
		}
		obj := g.objectOf(a)
		if v, ok := obj.(*types.Var); ok && isProviderSet(v.Type()) {
			if seen[v] {
				continue
			}
			seen[v] = true
			init := g.varInit(v)
			if init == nil {
				g.errorf(a.Pos(), "can't find the layer.Set that %s is declared with", v.Name())
				continue
			}
			out = append(out, g.providers([]ast.Expr{init}, false, seen)...)
			continue
		}
		t := g.pkg.TypesInfo.TypeOf(a)
		sig, ok := t.(*types.Signature)
		if !ok {
			g.errorf(a.Pos(), "%s is not a provider function", types.ExprString(a))
			continue
		}
		p := &provider{expr: a, sig: sig, direct: direct}
		rs := sig.Results()
		switch {
		case rs.Len() == 1:
			p.out = rs.At(0).Type()
		case rs.Len() == 2 && isError(rs.At(1).Type()):
			p.out, p.hasErr = rs.At(0).Type(), true
		case rs.Len() == 3 && isError(rs.At(2).Type()) && cleanupKind(rs.At(1).Type()) != "":
			p.out, p.hasErr, p.cleanup = rs.At(0).Type(), true, cleanupKind(rs.At(1).Type())
		default:
			g.errorf(a.Pos(), "%s: a provider returns T, (T, error) or (T, cleanup, error)", types.ExprString(a))
			continue
		}
		out = append(out, p)
	}
	return out
}

func (g *gen) objectOf(x ast.Expr) types.Object {
	switch x := x.(type) {
	case *ast.Ident:
		return g.pkg.TypesInfo.Uses[x]
	case *ast.SelectorExpr:
		return g.pkg.TypesInfo.Uses[x.Sel]
	}
	return nil
}

func (g *gen) varInit(v *types.Var) ast.Expr {
	for _, f := range g.pkg.Syntax {
		for _, d := range f.Decls {
			gd, ok := d.(*ast.GenDecl)
			if !ok || gd.Tok != token.VAR {
				continue
			}
			for _, s := range gd.Specs {
				vs := s.(*ast.ValueSpec)
				for i, n := range vs.Names {
					if g.pkg.TypesInfo.Defs[n] == v && i < len(vs.Values) {
						return vs.Values[i]
					}
				}
			}
		}
	}
	return nil
}

func isProviderSet(t types.Type) bool { return typeutil.IsNamed(t, layerPath, "ProviderSet") }

var (
	isError   = typeutil.IsError
	isContext = typeutil.IsContext
)

func isScope(t types.Type) bool {
	p, ok := t.(*types.Pointer)
	return ok && typeutil.IsNamed(p.Elem(), scopePath, "Scope")
}

func cleanupKind(t types.Type) string {
	sig, ok := t.(*types.Signature)
	if !ok || sig.Variadic() {
		return ""
	}
	switch {
	case sig.Params().Len() == 0 && sig.Results().Len() == 0:
		return "func()"
	case sig.Params().Len() == 0 && sig.Results().Len() == 1 && isError(sig.Results().At(0).Type()):
		return "func() error"
	case sig.Params().Len() == 1 && isContext(sig.Params().At(0).Type()) && sig.Results().Len() == 1 && isError(sig.Results().At(0).Type()):
		return "func(ctx) error"
	}
	return ""
}

func hasClose(t types.Type) bool {
	obj, _, _ := types.LookupFieldOrMethod(t, true, nil, "Close")
	f, ok := obj.(*types.Func)
	if !ok {
		return false
	}
	sig := f.Signature()
	return sig.Params().Len() == 0 && (sig.Results().Len() == 0 || sig.Results().Len() == 1 && isError(sig.Results().At(0).Type()))
}

func closeReturnsError(t types.Type) bool {
	obj, _, _ := types.LookupFieldOrMethod(t, true, nil, "Close")
	return obj.(*types.Func).Signature().Results().Len() == 1
}

// injector generates one injector function.
func (g *gen) injector(fd *ast.FuncDecl, args []ast.Expr) (string, bool) {
	before := len(g.diags)
	name := fd.Name.Name
	obj := g.pkg.TypesInfo.Defs[fd.Name].(*types.Func)
	sig := obj.Signature()
	if sig.Results().Len() != 2 || !isError(sig.Results().At(1).Type()) {
		g.errorf(fd.Pos(), "%s: an injector returns (T, error)", name)
		return "", false
	}
	want := sig.Results().At(0).Type()
	ps := g.providers(args, true, map[types.Object]bool{})

	b := &builder{g: g, fn: name, pos: fd.Body.List[0].Pos(), vals: map[string]string{}, names: map[string]bool{}, building: map[*provider]bool{}, zero: g.zero(want)}
	// The injector's parameters are inputs.
	for i := 0; i < sig.Params().Len(); i++ {
		v := sig.Params().At(i)
		pname := v.Name()
		if pname == "" || pname == "_" {
			g.errorf(fd.Pos(), "%s: name every parameter", name)
			return "", false
		}
		b.names[pname] = true
		b.inputs = append(b.inputs, input{pname, v.Type()})
		if isContext(v.Type()) {
			b.ctx = pname
		}
		if isScope(v.Type()) {
			b.scope = pname
		}
	}
	// Direct providers take precedence over those from sets.
	byType := map[string][]*provider{}
	for _, p := range ps {
		key := types.TypeString(p.out, nil)
		byType[key] = append(byType[key], p)
	}
	for key, list := range byType {
		var direct []*provider
		for _, p := range list {
			if p.direct {
				direct = append(direct, p)
			}
		}
		if len(direct) > 0 {
			list = direct
		}
		if len(list) > 1 {
			var names []string
			for _, p := range list {
				names = append(names, p.name())
			}
			g.errorf(fd.Pos(), "%s: several providers for %s: %s", name, key, strings.Join(names, ", "))
			return "", false
		}
		b.providers = append(b.providers, list[0])
	}
	sort.Slice(b.providers, func(i, j int) bool { return b.providers[i].expr.Pos() < b.providers[j].expr.Pos() })

	result := b.resolve(want, "the result of "+name, nil)
	if len(g.diags) > before {
		return "", false
	}
	for _, p := range b.providers {
		if p.direct && !p.used {
			g.errorf(p.expr.Pos(), "%s: %s is not needed", name, p.name())
		}
	}
	if len(g.diags) > before {
		return "", false
	}

	var out strings.Builder
	if fd.Doc != nil {
		for _, c := range fd.Doc.List {
			out.WriteString(c.Text + "\n")
		}
	}
	out.WriteString("func " + name + "(")
	for i, in := range b.inputs {
		if i > 0 {
			out.WriteString(", ")
		}
		out.WriteString(in.name + " " + g.typeString(in.typ))
	}
	out.WriteString(") (" + g.typeString(want) + ", error) {\n")
	out.WriteString(b.body.String())
	out.WriteString("return " + result + ", nil\n}\n")
	return out.String(), true
}

type input struct {
	name string
	typ  types.Type
}

// builder writes the body of one injector.
type builder struct {
	g         *gen
	fn        string
	pos       token.Pos // the layer.Build call, where graph errors are reported
	inputs    []input
	ctx       string
	scope     string
	providers []*provider
	vals      map[string]string // type string -> variable
	names     map[string]bool
	building  map[*provider]bool
	body      strings.Builder
	zero      string
}

// resolve returns the variable holding a value of type t, building it.
func (b *builder) resolve(t types.Type, neededBy string, chain []string) string {
	key := types.TypeString(t, nil)
	if v, ok := b.vals[key]; ok {
		return v
	}
	for _, in := range b.inputs {
		if types.Identical(in.typ, t) {
			return in.name
		}
	}
	var p *provider
	for _, q := range b.providers {
		if types.Identical(q.out, t) {
			p = q
		}
	}
	if p == nil {
		if iface, ok := t.Underlying().(*types.Interface); ok {
			var cands []*provider
			for _, q := range b.providers {
				if types.Implements(q.out, iface) {
					cands = append(cands, q)
				}
			}
			// Direct providers win, as for exact types.
			var direct []*provider
			for _, q := range cands {
				if q.direct {
					direct = append(direct, q)
				}
			}
			if len(direct) > 0 {
				cands = direct
			}
			for _, in := range b.inputs {
				if types.Implements(in.typ, iface) && !isContext(in.typ) {
					return in.name
				}
			}
			switch len(cands) {
			case 1:
				p = cands[0]
			case 0:
			default:
				var names []string
				for _, q := range cands {
					names = append(names, q.name())
				}
				b.g.errorf(b.pos, "%s: several providers implement %s, needed by %s: %s", b.fn, b.g.typeString(t), neededBy, strings.Join(names, ", "))
				return "nil"
			}
		}
	}
	if p == nil {
		pos := token.NoPos
		if len(b.providers) > 0 {
			pos = b.providers[0].expr.Pos()
		}
		_ = pos
		b.g.errorf(b.pos, "%s: no provider for %s, needed by %s", b.fn, b.g.typeString(t), neededBy)
		return "nil"
	}
	if b.building[p] {
		b.g.errorf(b.pos, "%s: dependency cycle: %s", b.fn, strings.Join(append(chain, p.name()), " → "))
		return "nil"
	}
	b.building[p] = true
	p.used = true
	var args []string
	for i := 0; i < p.sig.Params().Len(); i++ {
		pt := p.sig.Params().At(i).Type()
		switch {
		case isContext(pt) && b.ctx != "":
			args = append(args, b.ctx)
		case isScope(pt) && b.scope != "":
			args = append(args, b.scope)
		default:
			args = append(args, b.resolve(pt, p.name(), append(chain, p.name())))
		}
	}
	v := b.varName(p.out)
	call := b.g.exprString(p.expr) + "(" + strings.Join(args, ", ") + ")"
	needsScope := p.close || p.cleanup != ""
	if needsScope && b.scope == "" {
		b.g.errorf(p.expr.Pos(), "%s: %s has a finalizer, so the injector needs a *scope.Scope parameter", b.fn, p.name())
	}
	switch {
	case p.cleanup != "":
		c := b.fresh("cleanup")
		fmt.Fprintf(&b.body, "%s, %s, err := %s\nif err != nil {\nreturn %s, %s\n}\n", v, c, call, b.zero, b.wrap(p))
		ctx := b.g.pkgName("context")
		switch p.cleanup {
		case "func()":
			fmt.Fprintf(&b.body, "%s.Defer(func(%s.Context) error { %s(); return nil })\n", b.scope, ctx, c)
		case "func() error":
			fmt.Fprintf(&b.body, "%s.Defer(func(%s.Context) error { return %s() })\n", b.scope, ctx, c)
		default:
			fmt.Fprintf(&b.body, "%s.Defer(%s)\n", b.scope, c)
		}
	case p.hasErr:
		fmt.Fprintf(&b.body, "%s, err := %s\nif err != nil {\nreturn %s, %s\n}\n", v, call, b.zero, b.wrap(p))
	default:
		fmt.Fprintf(&b.body, "%s := %s\n", v, call)
	}
	if p.close {
		ctx := b.g.pkgName("context")
		if closeReturnsError(p.out) {
			fmt.Fprintf(&b.body, "%s.Defer(func(%s.Context) error { return %s.Close() })\n", b.scope, ctx, v)
		} else {
			fmt.Fprintf(&b.body, "%s.Defer(func(%s.Context) error { %s.Close(); return nil })\n", b.scope, ctx, v)
		}
	}
	delete(b.building, p)
	b.vals[types.TypeString(p.out, nil)] = v
	return v
}

func (b *builder) wrap(p *provider) string {
	return b.g.pkgName("fmt") + ".Errorf(\"" + p.name() + ": %w\", err)"
}

func (g *gen) posOfInjector(name string) token.Pos {
	for _, f := range g.pkg.Syntax {
		for _, d := range f.Decls {
			if fd, ok := d.(*ast.FuncDecl); ok && fd.Name.Name == name && isInjectorFile(g.pkg.Fset.File(f.Pos()).Name()) {
				return fd.Name.Pos()
			}
		}
	}
	return token.NoPos
}

// varName names a variable after its type: *sql.DB -> db.
func (b *builder) varName(t types.Type) string {
	if p, ok := t.(*types.Pointer); ok {
		t = p.Elem()
	}
	base := "v"
	if n, ok := types.Unalias(t).(*types.Named); ok {
		r := []rune(n.Obj().Name())
		// Lowercase the leading capitals: DB -> db, HTTPClient -> httpClient.
		i := 0
		for i < len(r) && unicode.IsUpper(r[i]) && (i == 0 || i+1 >= len(r) || unicode.IsUpper(r[i+1])) {
			r[i] = unicode.ToLower(r[i])
			i++
		}
		base = string(r)
	}
	return b.fresh(base)
}

func (b *builder) fresh(base string) string {
	n := base
	for i := 2; b.names[n] || token.IsKeyword(n) || n == "err" || types.Universe.Lookup(n) != nil || b.g.pkg.Types.Scope().Lookup(n) != nil; i++ {
		n = base + strconv.Itoa(i)
	}
	b.names[n] = true
	return n
}

// exprString renders a provider expression, keeping its package qualifier
// imported.
func (g *gen) exprString(x ast.Expr) string {
	if sel, ok := x.(*ast.SelectorExpr); ok {
		if id, ok := sel.X.(*ast.Ident); ok {
			if pn, ok := g.pkg.TypesInfo.Uses[id].(*types.PkgName); ok {
				return g.pkgName(pn.Imported().Path()) + "." + sel.Sel.Name
			}
		}
	}
	return types.ExprString(x)
}

// pkgName returns the name to refer to a package by, importing it.
func (g *gen) pkgName(p string) string {
	if n, ok := g.imports[p]; ok {
		return n
	}
	name := path.Base(p)
	for _, f := range g.pkg.Syntax {
		for _, s := range f.Imports {
			if strings.Trim(s.Path.Value, `"`) == p && s.Name != nil {
				name = s.Name.Name
			}
		}
	}
	for _, imp := range g.pkg.Types.Imports() {
		if imp.Path() == p {
			name = imp.Name()
		}
	}
	g.imports[p] = name
	return name
}

func (g *gen) typeString(t types.Type) string {
	return types.TypeString(t, func(p *types.Package) string {
		if p == g.pkg.Types {
			return ""
		}
		return g.pkgName(p.Path())
	})
}

func (g *gen) zero(t types.Type) string { return typeutil.Zero(t, g.typeString) }
