// Code generated by ego generate from report.ego. DO NOT EDIT.

// Package report exercises the v1 shorthand: lambdas, ?. and ??, if and
// match expressions, and f-strings.
package report

import (
	"cmp"
	"fmt"
	"os"
	"slices"
	"strings"
)

//line report.ego:12
type Address struct{ City string }

type User struct {
	Name    string
	Address *Address
	Manager *User
}

type Order struct {
	Total float64
	Late  bool
}

func Summary(u *User, orders []Order) string {
	slices.SortFunc(orders, func(a, b Order) int { return cmp.Compare(b.Total, a.Total) })
	late := slices.ContainsFunc(orders, func(o Order) bool { return o.Late })
	city := "your address"
	if u != nil && u.Address != nil {
		city = u.Address.City
	}
//line report.ego:29
	var tone string
	if late {
		tone = "Sorry for the delay"
	} else {
		tone = "Good news"
	}
//line report.ego:30
	return fmt.Sprintf("%s! %d orders are on their way to %s.", tone, len(orders), city)
}

// Port reads PORT, with a default.
func Port() string {
	port, ok := os.LookupEnv("PORT")
	if !ok {
		port = "8080"
	}
//line report.ego:36
	return port
}

func Lookup(m map[string]int, k string) int {
	v, ok := m[k]
	if !ok {
		v = -1
	}
	return v
}

//line report.ego:43
func ManagerName(u *User) string {
	v := "nobody"
	if u != nil && u.Manager != nil {
		v = u.Manager.Name
	}
	return v
}

//line report.ego:47
func Grade(score int) string {
	var v string
	if score >= 90 {
		v = "A"
	} else if score >= 80 {
		v = "B"
	} else {
		v = "C"
	}
	return v
}

//line report.ego:51
func Total(orders []Order) string {
	sum := 0.0
	for _, o := range orders {
		sum += o.Total
	}
	return fmt.Sprintf("%.2f EUR, {braces} and 100%%", sum)
}

func Names(us []*User) []string {
	var out []string
	for _, u := range us {
		v := "?"
		if u != nil {
			v = u.Name
		}
		out = append(out, strings.ToUpper(v))
	}
//line report.ego:64
	return out
}

func Describe(n int) string {
	var kind string
	switch n % 2 {
	case 0:
		kind = "even"
	default:
		kind = "odd"
	}
//line report.ego:72
	return fmt.Sprintf("%d is %s", n, kind)
}

func Apply(xs []int, f func(int) int) []int {
	out := make([]int, len(xs))
	for i, x := range xs {
		out[i] = f(x)
	}
	return out
}

func Double(xs []int) []int {
	return Apply(xs, func(x int) int { return x * 2 })
}

func Typed() func(int) string {
	f := func(n int) string { return fmt.Sprintf("#%d", n) }
	return f
}
