// Code generated by ego generate from consumer_test.ego. DO NOT EDIT.

package users_test

import (
	"context"
	"testing"
	"time"

	"github.com/effect-go/effect-go/internal/egotest/consumer"
	"github.com/effect-go/effect-go/internal/egotest/users"
)

//line consumer_test.ego:12
type noUsers struct{}

func (noUsers) Find(context.Context, users.UserID) (users.User, bool, error) {
	return users.User{}, false, nil
}

// An external test importing a package that imports users, which has
// in-package tests too: both must see the same users, as go test compiles
// them.
func TestThroughConsumer(t *testing.T) {
	s := &users.Service{Repo: noUsers{}, Now: time.Now}
	if got := consumer.Status(t.Context(), s, "nobody"); got != 404 {
		t.Fatalf("Status: %d, want 404", got)
	}
}
