// Code generated by ego generate from users.ego. DO NOT EDIT.

package users

import (
	"context"
	"errors"
	"fmt"
	"net/http"
	"time"

	"github.com/effect-go/effect-go/scope"
	"github.com/effect-go/effect-go/trace"
)

//line users.ego:9
type UserID string

type User struct {
	ID             UserID
	Name           string
	SuspendedUntil time.Time
}

type Repo interface {
	Find(ctx context.Context, id UserID) (u User, found bool, err error)
}

// UserError is the error set NotFound | Suspended | Storage.
type UserError interface {
	error
	isUserError()
}

type NotFound struct{ ID UserID }

func (NotFound) isUserError() {}

func (e NotFound) Error() string { return fmt.Sprintf("not found (ID %v)", e.ID) }

type Suspended struct{ Until time.Time }

func (Suspended) isUserError() {}

func (e Suspended) Error() string { return fmt.Sprintf("suspended (Until %v)", e.Until) }

type Storage struct{ Cause error }

func (Storage) isUserError() {}

func (e Storage) Error() string { return fmt.Sprintf("storage: %v", e.Cause) }

func (e Storage) Unwrap() error { return e.Cause }

//line users.ego:27
type Service struct {
	Repo Repo
	Now  func() time.Time
}

func (s *Service) Get(ctx context.Context, id UserID) (_ User, err error) {
	ctx, span := trace.Start(ctx, "users.Service.Get")
	defer trace.End(span, &err)
//line users.ego:33
	u, ok, err := s.Repo.Find(ctx, id)
	if err != nil {
		return User{}, Storage{Cause: err}
	}
//line users.ego:34
	if !ok {
		return User{}, NotFound{ID: id}
	}
	if u.SuspendedUntil.After(s.Now()) {
		return User{}, Suspended{Until: u.SuspendedUntil}
	}
	return u, nil
}

type Handler struct{ Users *Service }

func (h *Handler) GetUser(w http.ResponseWriter, r *http.Request) {
	u, err := h.Users.Get(r.Context(), UserID(r.PathValue("id")))
	if err == nil {
		fmt.Fprintf(w, "%s\n", u.Name)
	} else if e, ok := errors.AsType[NotFound](err); ok {
//line users.ego:49
		http.Error(w, fmt.Sprintf("no user %s", e.ID), http.StatusNotFound)
	} else if e, ok := errors.AsType[Suspended](err); ok {
//line users.ego:50
		http.Error(w, fmt.Sprintf("suspended until %s", e.Until.Format(time.DateOnly)), http.StatusForbidden)
	} else if _, ok := errors.AsType[Storage](err); ok {
//line users.ego:51
		http.Error(w, "try again later", http.StatusServiceUnavailable)
	} else {
		panic(err)
	}
}

// GetAll loads users four at a time. Get's errors are passed on: they are
// the same set.
//
//line users.ego:55
func (s *Service) GetAll(ctx context.Context, ids []UserID) (_ []User, err error) {
	ctx, span := trace.Start(ctx, "users.Service.GetAll")
	defer trace.End(span, &err)
//line users.ego:58
	return scope.Each(ctx, ids, 4, func(ctx context.Context, id UserID) (User, error) { return s.Get(ctx, id) })
}

// GetEach takes the method itself, which receives each call's ctx.
func (s *Service) GetEach(ctx context.Context, ids []UserID) (_ []User, err error) {
	ctx, span := trace.Start(ctx, "users.Service.GetEach")
	defer trace.End(span, &err)
//line users.ego:63
	users, err := scope.Each(ctx, ids, 2, s.Get)
	if err != nil {
		return nil, fmt.Errorf("get users: %w", err)
	}
//line users.ego:64
	return users, nil
}

// AllExist runs a check that returns only an error on every id.
func (s *Service) AllExist(ctx context.Context, ids []UserID) (err error) {
	ctx, span := trace.Start(ctx, "users.Service.AllExist")
	defer trace.End(span, &err)
//line users.ego:69
	if _, err := scope.Each(ctx, ids, 8, func(ctx context.Context, id UserID) (struct{}, error) { return struct{}{}, s.exists(ctx, id) }); err != nil {
		return fmt.Errorf("s.exists: %w", err)
	}
//line users.ego:70
	return nil
}

func (s *Service) exists(ctx context.Context, id UserID) (err error) {
	ctx, span := trace.Start(ctx, "users.Service.exists")
	defer trace.End(span, &err)
//line users.ego:74
	if _, err := s.Get(ctx, id); err != nil {
		return fmt.Errorf("s.Get: %w", err)
	}
//line users.ego:75
	return nil
}
