// Code generated by ego generate from dashboard.ego. DO NOT EDIT.

// Package dashboard builds a user's home page from four services.
package dashboard

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/effect-go/effect-go/schedule"

	"github.com/effect-go/effect-go/scope"
	"github.com/effect-go/effect-go/trace"
)

//line dashboard.ego:11
type User struct {
	ID     string
	Name   string
	Banner string
}

type Order struct {
	ID    string
	Total int
}

type Product struct{ ID string }

type Image struct{ URL string }

type Page struct {
	User   User
	Orders []Order
	Recs   []Product
	Banner Image
}

type Deps struct {
	Users interface {
		Get(ctx context.Context, id string) (User, error)
	}
	Orders interface {
		ForUser(ctx context.Context, id string) ([]Order, error)
	}
	Recs interface {
		For(ctx context.Context, id string) ([]Product, error)
	}
	CDN interface {
		Primary(ctx context.Context, key string) (Image, error)
		Mirror(ctx context.Context, key string) (Image, error)
	}
}

// ErrRejected is a recommendation error that retrying won't fix.
var ErrRejected = errors.New("recommendations: request rejected")

var recsPolicy = schedule.Max(schedule.Exponential(100*time.Millisecond), schedule.Recurs(3)).
	Jittered().
	While(func(err error) bool { return !errors.Is(err, ErrRejected) })

// Load builds the page, giving up after two seconds.
func Load(ctx context.Context, d Deps, id string) (_ Page, err error) {
	ctx, span := trace.Start(ctx, "dashboard.Load")
	defer trace.End(span, &err)
//line dashboard.ego:58
	return scope.Timeout(ctx, 2*time.Second, func(ctx context.Context) (Page, error) { return load(ctx, d, id) })
}

func load(ctx context.Context, d Deps, id string) (_ Page, err error) {
	ctx, span := trace.Start(ctx, "dashboard.load")
	defer trace.End(span, &err)
//line dashboard.ego:62
	user, orders, recs, err := scope.All3(ctx,
		func(ctx context.Context) (User, error) { return d.Users.Get(ctx, id) },
		func(ctx context.Context) ([]Order, error) { return d.Orders.ForUser(ctx, id) },
		func(ctx context.Context) ([]Product, error) {
			return schedule.Retry(ctx, recsPolicy, func(ctx context.Context) ([]Product, error) { return d.Recs.For(ctx, id) })
		},
	)
	if err != nil {
		return Page{}, err
	}
//line dashboard.ego:63
	banner, err := scope.Race(ctx,
		func(ctx context.Context) (Image, error) { return d.CDN.Primary(ctx, user.Banner) },
		func(ctx context.Context) (Image, error) { return d.CDN.Mirror(ctx, user.Banner) },
	)
	if err != nil {
		return Page{}, fmt.Errorf("banner: %w", err)
	}
//line dashboard.ego:64
	return Page{User: user, Orders: orders, Recs: recs, Banner: banner}, nil
}
