// Code generated by ego generate from args.ego. DO NOT EDIT.

package main

import (
	"errors"
	"flag"
	"fmt"
	"io"
	"strconv"
	"strings"
	"time"
)

//line args.ego:13
const usage = `usage:
  todo add TITLE [-p low|medium|high] [-due YYYY-MM-DD]
  todo list [-all]
  todo done ID...
  todo rm ID...
  todo stats`

// An Action is what a command does. Matches on it must handle every one.
type Action int

const (
	Add Action = iota
	List
	Complete
	Remove
	ShowStats
)

func (v Action) String() string {
	switch v {
	case Add:
		return "Add"
	case List:
		return "List"
	case Complete:
		return "Complete"
	case Remove:
		return "Remove"
	case ShowStats:
		return "ShowStats"
	}
	return "Action(" + strconv.Itoa(int(v)) + ")"
}

// A Command is a parsed command line. Parsing needs no database, so a
// mistyped command fails before the app connects.
//
//line args.ego:31
type Command struct {
	Action   Action
	Title    string
	Priority Priority
	Due      *time.Time
	All      bool
	IDs      []int64
}

// ParseArgs parses the command line.
func ParseArgs(args []string) (Command, error) {
	if len(args) == 0 {
		return Command{}, Usage{Cause: errors.New("no command")}
	}
	var cmd Command
	name := args[0]
	fs := flag.NewFlagSet(name, flag.ContinueOnError)
	fs.SetOutput(io.Discard)
	words, flags := splitFlags(args[1:])
	switch name {
	case "add":

//line args.ego:52
		cmd.Action = Add
		prio := fs.String("p", "medium", "priority")
		due := fs.String("due", "", "due date")
		if err := fs.Parse(flags); err != nil {
			if _, ok := errors.AsType[TodoError](err); ok {
				return Command{}, err
			}
			return Command{}, Usage{Cause: err}
		}
//line args.ego:56
		cmd.Title = strings.Join(words, " ")
		v, err := ParsePriority(*prio)
		if err != nil {
			return Command{}, err
		}
		cmd.Priority = v
//line args.ego:58
		v2, err := ParseDue(*due)
		if err != nil {
			return Command{}, err
		}
		cmd.Due = v2

	case "list":

//line args.ego:61
		cmd.Action = List
		all := fs.Bool("all", false, "include done todos")
		if err := fs.Parse(flags); err != nil {
			if _, ok := errors.AsType[TodoError](err); ok {
				return Command{}, err
			}
			return Command{}, Usage{Cause: err}
		}
//line args.ego:64
		cmd.All = *all

	case "done", "rm":

//line args.ego:67
		if name == "done" {
			cmd.Action = Complete
		} else {
			cmd.Action = Remove
		}
//line args.ego:68
		if err := fs.Parse(flags); err != nil {
			if _, ok := errors.AsType[TodoError](err); ok {
				return Command{}, err
			}
			return Command{}, Usage{Cause: err}
		}
//line args.ego:69
		if len(words) == 0 {
			return Command{}, Usage{Cause: errors.New(fmt.Sprintf("%s takes the IDs of todos", name))}
		}
		for _, w := range words {
			id, err := strconv.ParseInt(w, 10, 64)
			if err != nil {
				if _, ok := errors.AsType[TodoError](err); ok {
					return Command{}, err
				}
				return Command{}, Invalid{Reason: fmt.Sprintf("bad id %q", w)}
			}
//line args.ego:74
			cmd.IDs = append(cmd.IDs, id)
		}

	case "stats":

//line args.ego:78
		cmd.Action = ShowStats
		if err := fs.Parse(flags); err != nil {
			if _, ok := errors.AsType[TodoError](err); ok {
				return Command{}, err
			}
			return Command{}, Usage{Cause: err}
		}

	default:
//line args.ego:81
		return Command{}, Usage{Cause: errors.New(fmt.Sprintf("unknown command %q", name))}
	}
	return cmd, nil
}

// splitFlags separates a command's words from its flags, so both
// "add buy milk -p high" and "add -p high buy milk" work.
func splitFlags(args []string) (words, flags []string) {
	for i := 0; i < len(args); i++ {
		a := args[i]
		if !strings.HasPrefix(a, "-") {
			words = append(words, a)
			continue
		}
		flags = append(flags, a)
		if !strings.Contains(a, "=") && i+1 < len(args) && !strings.HasPrefix(args[i+1], "-") && a != "-all" {
			i++
			flags = append(flags, args[i]) // the flag's value
		}
	}
	return words, flags
}

// Report writes err for the user and returns the exit code: 1 for a
// missing todo, 2 for bad input, 3 when the database fails.
func Report(w io.Writer, err error) int {
	if err == nil {
		return 0
	} else if e, ok := errors.AsType[NotFound](err); ok {

//line args.ego:110
		fmt.Fprintln(w, e)
		return 1

	} else if e, ok := errors.AsType[Invalid](err); ok {

//line args.ego:114
		fmt.Fprintln(w, e)
		return 2

	} else if e, ok := errors.AsType[Usage](err); ok {

//line args.ego:118
		fmt.Fprintln(w, e)
		fmt.Fprintln(w, usage)
		return 2

	} else if e, ok := errors.AsType[Storage](err); ok {

//line args.ego:123
		fmt.Fprintln(w, e)
		return 3

	} else {

//line args.ego:127
		fmt.Fprintln(w, err) // a timeout
		return 1

	}
}
