// Code generated by ego generate from cli.ego. DO NOT EDIT.

package main

import (
	"context"
	"fmt"
	"io"
	"time"

	"github.com/effect-go/effect-go/scope"
	"github.com/effect-go/effect-go/trace"
)

// Config is what the app needs from its environment.
//
//line cli.ego:9
type Config struct {
	DatabaseURL string
	Out, Err    io.Writer
}

// CLI runs commands.
type CLI struct {
	svc      *Service
	now      Clock
	out, err io.Writer
}

func NewCLI(svc *Service, now Clock, cfg Config) *CLI { return &CLI{svc, now, cfg.Out, cfg.Err} }

// Run runs a command, gives it 10 seconds, and returns the exit code.
func (c *CLI) Run(ctx context.Context, cmd Command) (_ int) {
	ctx, span := trace.Start(ctx, "main.CLI.Run")
	defer trace.End(span, nil)
//line cli.ego:26
	_, err := scope.Timeout(ctx, 10*time.Second, func(ctx context.Context) (struct{}, error) { return struct{}{}, c.run(ctx, cmd) })
	return Report(c.err, err)
}

func (c *CLI) run(ctx context.Context, cmd Command) (err error) {
	ctx, span := trace.Start(ctx, "main.CLI.run")
	defer trace.End(span, &err)
//line cli.ego:31
	switch cmd.Action {
	case Add:

//line cli.ego:33
		t, err := c.svc.Add(ctx, cmd.Title, cmd.Priority, cmd.Due)
		if err != nil {
			return fmt.Errorf("svc.Add: %w", err)
		}
//line cli.ego:34
		fmt.Fprintln(c.out, fmt.Sprintf("added #%d: %s", t.ID, t.Title))

	case List:
//line cli.ego:36
		if err := c.list(ctx, cmd.All); err != nil {
			return fmt.Errorf("c.list: %w", err)
		}
	case Complete:
//line cli.ego:37
		if _, err := scope.Each(ctx, cmd.IDs, 4, func(ctx context.Context, id int64) (struct{}, error) { return struct{}{}, c.svc.Done(ctx, id) }); err != nil {
			return fmt.Errorf("svc.Done: %w", err)
		}
	case Remove:
//line cli.ego:38
		if _, err := scope.Each(ctx, cmd.IDs, 4, func(ctx context.Context, id int64) (struct{}, error) { return struct{}{}, c.svc.Remove(ctx, id) }); err != nil {
			return fmt.Errorf("svc.Remove: %w", err)
		}
	case ShowStats:

//line cli.ego:40
		s, err := c.svc.Stats(ctx)
		if err != nil {
			return fmt.Errorf("svc.Stats: %w", err)
		}
//line cli.ego:41
		fmt.Fprintln(c.out, fmt.Sprintf("%d open, %d done, %d overdue", s.Open, s.Done, s.Overdue))

	}
	return nil
}

func (c *CLI) list(ctx context.Context, all bool) (err error) {
	ctx, span := trace.Start(ctx, "main.CLI.list")
	defer trace.End(span, &err)
//line cli.ego:48
	todos, err := c.svc.List(ctx, all)
	if err != nil {
		return fmt.Errorf("svc.List: %w", err)
	}
//line cli.ego:49
	if len(todos) == 0 {
		fmt.Fprintln(c.out, "nothing to do")
	}
	now := c.now()
	for _, t := range todos {
		var mark string
		if t.DoneAt != nil {
			mark = "x"
		} else {
			mark = " "
		}
//line cli.ego:55
		due := ""
		if t.Due != nil {
			due = t.Due.Format(time.DateOnly)
		}
//line cli.ego:56
		if t.Overdue(now) {
			due += " (overdue)"
		}
		fmt.Fprintln(c.out, fmt.Sprintf("[%s] #%-3d %-6s %s  %s", mark, t.ID, t.Priority, t.Title, due))
	}
	return nil
}
