// Code generated by ego generate from config.ego. DO NOT EDIT.

package main

import "os"

// databaseURL is TODO_DATABASE_URL, or a local database named todo.
//
//line config.ego:6
func databaseURL() string {
	url, ok := os.LookupEnv("TODO_DATABASE_URL")
	if !ok {
		url = "postgres://localhost:5432/todo?sslmode=disable"
	}
//line config.ego:8
	return url
}
