// Code generated by ego generate. DO NOT EDIT.

//go:build !egolayers

package main

import (
	"context"
	"fmt"

	"github.com/effect-go/effect-go/scope"
)

// BuildCLI builds the CLI on PostgreSQL.
func BuildCLI(ctx context.Context, s *scope.Scope, cfg Config) (*CLI, error) {
	pool, err := Connect(ctx, cfg)
	if err != nil {
		return nil, fmt.Errorf("Connect: %w", err)
	}
	s.Defer(func(context.Context) error { pool.Close(); return nil })
	pgStore := NewPgStore(pool)
	clock := NewClock()
	service := NewService(pgStore, clock)
	cli := NewCLI(service, clock, cfg)
	return cli, nil
}

// BuildTestCLI swaps the database for memory and the clock for clock.
func BuildTestCLI(ctx context.Context, s *scope.Scope, cfg Config, clock Clock) (*CLI, error) {
	memStore := NewMemStore()
	service := NewService(memStore, clock)
	cli := NewCLI(service, clock, cfg)
	return cli, nil
}
