// Code generated by ego generate from main.ego. DO NOT EDIT.

package main

import (
	"context"
	"os"
	"os/signal"

	"github.com/effect-go/effect-go/scope"
	"github.com/effect-go/effect-go/trace"
)

//line main.ego:9
func main() {
	ctx, stop := signal.NotifyContext(context.Background(), os.Interrupt)
	code, err := scope.Run(ctx, func(s *scope.Scope) (int, error) { return run(s, os.Args[1:]) })
	stop()
	var v int
	if err != nil {
		v = Report(os.Stderr, err)
	} else {
		v = code
	}
	os.Exit(v)
}

// run parses the command line before anything connects, then builds the app
// in s, with the generated BuildCLI, and runs the command. The scope closes
// the database pool when it ends.
//
//line main.ego:19
func run(s *scope.Scope, args []string) (_ int, err error) {
	ctx, span := trace.Start(s.Context(), "main.run")
	defer trace.End(span, &err)
//line main.ego:20
	cmd, err := ParseArgs(args)
	if err != nil {
		return 0, err
	}
//line main.ego:21
	cli, err := BuildCLI(ctx, s, Config{DatabaseURL: databaseURL(), Out: os.Stdout, Err: os.Stderr})
	if err != nil {
		return 0, Storage{Cause: err}
	}
//line main.ego:22
	return cli.Run(ctx, cmd), nil
}
