// Code generated by ego generate from memstore.ego. DO NOT EDIT.

package main

import (
	"context"
	"slices"
	"sync"
	"time"

	"github.com/effect-go/effect-go/trace"
)

// MemStore is an in-memory Store, for tests: the test graph swaps it in for
// PgStore.
//
//line memstore.ego:11
type MemStore struct {
	mu    sync.Mutex
	next  int64
	todos []Todo
}

func NewMemStore() *MemStore { return &MemStore{} }

func (m *MemStore) Insert(ctx context.Context, t Todo) (_ Todo, err error) {
	ctx, span := trace.Start(ctx, "main.MemStore.Insert")
	defer trace.End(span, &err)
	m.mu.Lock()
	defer m.mu.Unlock()
	m.next++
	t.ID = m.next
	m.todos = append(m.todos, t)
	return t, nil
}

//line memstore.ego:28
func (m *MemStore) List(ctx context.Context) (_ []Todo, err error) {
	ctx, span := trace.Start(ctx, "main.MemStore.List")
	defer trace.End(span, &err)
	m.mu.Lock()
	defer m.mu.Unlock()
	return slices.Clone(m.todos), nil
}

//line memstore.ego:34
func (m *MemStore) Complete(ctx context.Context, id int64, at time.Time) (_ bool, err error) {
	ctx, span := trace.Start(ctx, "main.MemStore.Complete")
	defer trace.End(span, &err)
//line memstore.ego:35
	m.mu.Lock()
	defer m.mu.Unlock()
	i := slices.IndexFunc(m.todos, func(t Todo) bool { return t.ID == id })
	if i < 0 {
		return false, nil
	}
	if m.todos[i].DoneAt == nil {
		m.todos[i].DoneAt = &at
	}
	return true, nil
}

func (m *MemStore) Delete(ctx context.Context, id int64) (_ bool, err error) {
	ctx, span := trace.Start(ctx, "main.MemStore.Delete")
	defer trace.End(span, &err)
//line memstore.ego:48
	m.mu.Lock()
	defer m.mu.Unlock()
	n := len(m.todos)
	m.todos = slices.DeleteFunc(m.todos, func(t Todo) bool { return t.ID == id })
	return len(m.todos) < n, nil
}

func (m *MemStore) Count(ctx context.Context, f Filter, now time.Time) (_ int, err error) {
	ctx, span := trace.Start(ctx, "main.MemStore.Count")
	defer trace.End(span, &err)
//line memstore.ego:56
	m.mu.Lock()
	defer m.mu.Unlock()
	n := 0
	for _, t := range m.todos {
		var ok bool
		switch f {
		case Open:
			ok = t.DoneAt == nil
		case Done:
			ok = t.DoneAt != nil
		case Overdue:
			ok = t.Overdue(now)
		default:
			panic(f)
		}
//line memstore.ego:65
		if ok {
			n++
		}
	}
	return n, nil
}
