// Code generated by ego generate from parse_test.ego. DO NOT EDIT.

package main

import (
	"errors"
	"testing"
	"time"
)

// Tests can be written in effect-go too: match checks every error case.
//
//line parse_test.ego:8
func TestParse(t *testing.T) {
	for in, want := range map[string]string{"": "Medium", "HIGH": "High", "low": "Low", "x": "invalid"} {
		p, err := ParsePriority(in)
		var got string
		if err == nil {
			got = p.String()
		} else if _, ok := errors.AsType[Invalid](err); ok {
			got = "invalid"
		} else {
			got = err.Error()
		}
//line parse_test.ego:17
		if got != want {
			t.Errorf("ParsePriority(%q) = %s, want %s", in, got, want)
		}
	}
	due, err := ParseDue("2026-10-20")
	if err != nil {
		panic(err)
	}
//line parse_test.ego:22
	none, err := ParseDue("")
	if err != nil {
		panic(err)
	}
//line parse_test.ego:23
	if due.Format(time.DateOnly) != "2026-10-20" || none != nil {
		t.Fatal(due, none)
	}
}
