// Code generated by ego generate from service.ego. DO NOT EDIT.

package main

import (
	"cmp"
	"context"
	"fmt"
	"slices"
	"strings"
	"time"

	"github.com/effect-go/effect-go/scope"
	"github.com/effect-go/effect-go/trace"
)

// Clock is the current time; tests swap it.
//
//line service.ego:10
type Clock func() time.Time

func NewClock() Clock { return time.Now }

// Service is what the commands do. Its methods return the TodoError set.
type Service struct {
	store Store
	now   Clock
}

func NewService(store Store, now Clock) *Service { return &Service{store, now} }

func (s *Service) Add(ctx context.Context, title string, p Priority, due *time.Time) (_ Todo, err error) {
	ctx, span := trace.Start(ctx, "main.Service.Add")
	defer trace.End(span, &err)
//line service.ego:24
	title = strings.TrimSpace(title)
	if title == "" {
		return Todo{}, Invalid{Reason: "a todo needs a title"}
	}
	t, err := s.store.Insert(ctx, Todo{Title: title, Priority: p, Due: due})
	if err != nil {
		return Todo{}, Storage{Cause: err}
	}
//line service.ego:29
	return t, nil
}

// List returns the todos, most urgent first: by priority, then due date.
func (s *Service) List(ctx context.Context, all bool) (_ []Todo, err error) {
	ctx, span := trace.Start(ctx, "main.Service.List")
	defer trace.End(span, &err)
//line service.ego:34
	todos, err := s.store.List(ctx)
	if err != nil {
		return nil, Storage{Cause: err}
	}
//line service.ego:35
	if !all {
		todos = slices.DeleteFunc(todos, func(t Todo) bool { return t.DoneAt != nil })
	}
	slices.SortFunc(todos, func(a, b Todo) int {
		return cmp.Or(
			cmp.Compare(b.Priority, a.Priority),
			compareDue(a.Due, b.Due),
			cmp.Compare(a.ID, b.ID),
		)
	})
	return todos, nil
}

// compareDue orders by due date, with no date last.
func compareDue(a, b *time.Time) int {
	var v int
	if a == nil && b == nil {
		v = 0
	} else if a == nil {
		v = 1
	} else if b == nil {
		v = -1
	} else {
		v = a.Compare(*b)
	}
	return v
}

//line service.ego:51
func (s *Service) Done(ctx context.Context, id int64) (err error) {
	ctx, span := trace.Start(ctx, "main.Service.Done")
	defer trace.End(span, &err)
//line service.ego:52
	found, err := s.store.Complete(ctx, id, s.now())
	if err != nil {
		return Storage{Cause: err}
	}
//line service.ego:53
	if !found {
		return NotFound{ID: id}
	}
	return nil
}

func (s *Service) Remove(ctx context.Context, id int64) (err error) {
	ctx, span := trace.Start(ctx, "main.Service.Remove")
	defer trace.End(span, &err)
//line service.ego:60
	found, err := s.store.Delete(ctx, id)
	if err != nil {
		return Storage{Cause: err}
	}
//line service.ego:61
	if !found {
		return NotFound{ID: id}
	}
	return nil
}

// Stats are the counts the stats command shows.
type Stats struct{ Open, Done, Overdue int }

// Stats runs the three counts in parallel.
func (s *Service) Stats(ctx context.Context) (_ Stats, err error) {
	ctx, span := trace.Start(ctx, "main.Service.Stats")
	defer trace.End(span, &err)
//line service.ego:72
	now := s.now()
	open, done, overdue, err := scope.All3(ctx,
		func(ctx context.Context) (int, error) { return s.store.Count(ctx, Open, now) },
		func(ctx context.Context) (int, error) { return s.store.Count(ctx, Done, now) },
		func(ctx context.Context) (int, error) { return s.store.Count(ctx, Overdue, now) },
	)
	if err != nil {
		return Stats{}, Storage{Cause: err}
	}
//line service.ego:74
	return Stats{open, done, overdue}, nil
}

// ParsePriority reads a priority flag.
func ParsePriority(s string) (Priority, error) {
	switch strings.ToLower(s) {
	case "", "medium":
//line service.ego:80
		return Medium, nil
	case "low":
//line service.ego:81
		return Low, nil
	case "high":
//line service.ego:82
		return High, nil
	default:
//line service.ego:83
		return 0, Invalid{Reason: fmt.Sprintf("unknown priority %q: use low, medium or high", s)}
	}
}

// ParseDue reads a due date flag.
func ParseDue(s string) (*time.Time, error) {
	if s == "" {
		return nil, nil
	}
	d, err := time.Parse(time.DateOnly, s)
	if err != nil {
		return nil, Invalid{Reason: fmt.Sprintf("bad due date %q: use YYYY-MM-DD", s)}
	}
//line service.ego:93
	return &d, nil
}
