// Code generated by ego generate from store.ego. DO NOT EDIT.

package main

import (
	"context"
	"errors"
	"fmt"
	"io"
	"strconv"
	"time"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"

	"github.com/effect-go/effect-go/schedule"
	"github.com/effect-go/effect-go/trace"
)

// Store keeps the todos. Its methods are effect methods: they take a ctx,
// which callers in effect functions pass without writing it.
//
//line store.ego:15
type Store interface {
	Insert(ctx context.Context, t Todo) (Todo, error)
	List(ctx context.Context) ([]Todo, error)
	Complete(ctx context.Context, id int64, at time.Time) (found bool, err error)
	Delete(ctx context.Context, id int64) (found bool, err error)
	Count(ctx context.Context, f Filter, now time.Time) (int, error)
}

// Filter selects todos to count.
type Filter int

const (
	Open Filter = iota
	Done
	Overdue
)

func (v Filter) String() string {
	switch v {
	case Open:
		return "Open"
	case Done:
		return "Done"
	case Overdue:
		return "Overdue"
	}
	return "Filter(" + strconv.Itoa(int(v)) + ")"
}

// PgStore is the PostgreSQL store.
//
//line store.ego:31
type PgStore struct{ db *pgxpool.Pool }

func NewPgStore(db *pgxpool.Pool) *PgStore { return &PgStore{db} }

const schema = `CREATE TABLE IF NOT EXISTS todos (
	id         bigserial PRIMARY KEY,
	title      text NOT NULL,
	priority   int NOT NULL DEFAULT 0,
	due        date,
	done_at    timestamptz,
	created_at timestamptz NOT NULL DEFAULT now()
)`

// connectRetry retries a failed connection: the database may still be
// starting, as with docker compose. A bad URL won't get better, so it isn't
// retried.
var connectRetry = schedule.Max(schedule.Exponential(200*time.Millisecond), schedule.Recurs(4)).
	Jittered().
	While(func(err error) bool { return !errors.Is(err, errBadURL) })

var errBadURL = errors.New("bad database URL")

// Connect opens the pool, waiting for the database, and creates the table.
func Connect(ctx context.Context, cfg Config) (_ *pgxpool.Pool, err error) {
	ctx, span := trace.Start(ctx, "main.Connect")
	defer trace.End(span, &err)
//line store.ego:55
	w := cfg.Err
	if w == nil {
		w = io.Discard
	}
//line store.ego:56
	policy := connectRetry.Tap(func(n int, err error, wait time.Duration) {
		fmt.Fprintln(w, fmt.Sprintf("waiting for the database (attempt %d in %v)", n+1, wait.Round(time.Millisecond)))
	})
	db, err := schedule.Retry(ctx, policy, func(ctx context.Context) (*pgxpool.Pool, error) { return open(ctx, cfg.DatabaseURL) })
	if err != nil {
		return nil, fmt.Errorf("connect to the database: %w", err)
	}
//line store.ego:58
	if _, err := db.Exec(ctx, schema); err != nil {
		return nil, fmt.Errorf("create the todos table: %w", err)
	}
//line store.ego:59
	return db, nil
}

func open(ctx context.Context, url string) (_ *pgxpool.Pool, err error) {
	ctx, span := trace.Start(ctx, "main.open")
	defer trace.End(span, &err)
//line store.ego:63
	pc, err := pgxpool.ParseConfig(url)
	if err != nil {
		return nil, errors.Join(errBadURL, err)
	}
	db, err2 := pgxpool.NewWithConfig(ctx, pc)
	if err2 != nil {
		return nil, fmt.Errorf("pgxpool.NewWithConfig: %w", err2)
	}
//line store.ego:68
	if err := db.Ping(ctx); err != nil {
		db.Close()
		return nil, err
	}
	return db, nil
}

func (s *PgStore) Insert(ctx context.Context, t Todo) (_ Todo, err error) {
	ctx, span := trace.Start(ctx, "main.PgStore.Insert")
	defer trace.End(span, &err)
//line store.ego:76
	row := s.db.QueryRow(ctx, `INSERT INTO todos (title, priority, due) VALUES ($1, $2, $3) RETURNING id, created_at`, t.Title, t.Priority, t.Due)
	if err := row.Scan(&t.ID, &t.CreatedAt); err != nil {
		return Todo{}, fmt.Errorf("row.Scan: %w", err)
	}
//line store.ego:78
	return t, nil
}

func (s *PgStore) List(ctx context.Context) (_ []Todo, err error) {
	ctx, span := trace.Start(ctx, "main.PgStore.List")
	defer trace.End(span, &err)
//line store.ego:82
	rows, err := s.db.Query(ctx, `SELECT id, title, priority, due, done_at, created_at FROM todos`)
	if err != nil {
		return nil, fmt.Errorf("db.Query: %w", err)
	}
//line store.ego:83
	return pgx.CollectRows(rows, pgx.RowToStructByName[Todo])
}

// Complete marks a todo done. One already done keeps its first time.
func (s *PgStore) Complete(ctx context.Context, id int64, at time.Time) (_ bool, err error) {
	ctx, span := trace.Start(ctx, "main.PgStore.Complete")
	defer trace.End(span, &err)
	return s.found(ctx, `UPDATE todos SET done_at = coalesce(done_at, $2) WHERE id = $1 RETURNING true`, id, at)
}

//line store.ego:91
func (s *PgStore) Delete(ctx context.Context, id int64) (_ bool, err error) {
	ctx, span := trace.Start(ctx, "main.PgStore.Delete")
	defer trace.End(span, &err)
	return s.found(ctx, `DELETE FROM todos WHERE id = $1 RETURNING true`, id)
}

// found runs a statement that returns a row for the todo it changed, and
// reports whether there was one.
//
//line store.ego:97
func (s *PgStore) found(ctx context.Context, sql string, args ...any) (_ bool, err error) {
	ctx, span := trace.Start(ctx, "main.PgStore.found")
	defer trace.End(span, &err)
//line store.ego:98
	rows, err := s.db.Query(ctx, sql, args...)
	if err != nil {
		return false, fmt.Errorf("db.Query: %w", err)
	}
//line store.ego:99
	found, err := pgx.CollectExactlyOneRow(rows, pgx.RowTo[bool])
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			found = false
		} else {
			return false, fmt.Errorf("pgx.CollectExactlyOneRow: %w", err)
		}
	}
//line store.ego:100
	return found, nil
}

func (s *PgStore) Count(ctx context.Context, f Filter, now time.Time) (_ int, err error) {
	ctx, span := trace.Start(ctx, "main.PgStore.Count")
	defer trace.End(span, &err)
//line store.ego:104
	var where string
	switch f {
	case Open:
		where = "done_at IS NULL"
	case Done:
		where = "done_at IS NOT NULL"
	case Overdue:
		where = "done_at IS NULL AND due < $1::date"
	default:
		panic(f)
	}
//line store.ego:109
	var n int
	var args []any
	if f == Overdue {
		args = []any{now}
	} else {
		args = nil
	}
//line store.ego:111
	if err := s.db.QueryRow(ctx, `SELECT count(*) FROM todos WHERE `+where, args...).Scan(&n); err != nil {
		return 0, fmt.Errorf("QueryRow.Scan: %w", err)
	}
//line store.ego:112
	return n, nil
}
