// Code generated by ego generate from todo.ego. DO NOT EDIT.

// Command todo is a todo list on PostgreSQL, written in effect-go.
//
//	todo add "Buy milk" -p high -due 2026-10-10
//	todo list [-all]
//	todo done 3
//	todo rm 3
//	todo stats
//
// The database is TODO_DATABASE_URL, or a local "todo" database.
package main

import (
	"fmt"
	"strconv"
	"time"
)

// Priority orders the list: an enum without data compiles to constants.
//
//line todo.ego:14
type Priority int

const (
	Low Priority = iota
	Medium
	High
)

func (v Priority) String() string {
	switch v {
	case Low:
		return "Low"
	case Medium:
		return "Medium"
	case High:
		return "High"
	}
	return "Priority(" + strconv.Itoa(int(v)) + ")"
}

// A Todo is one item.
//
//line todo.ego:21
type Todo struct {
	ID        int64      `db:"id"`
	Title     string     `db:"title"`
	Priority  Priority   `db:"priority"`
	Due       *time.Time `db:"due"`
	DoneAt    *time.Time `db:"done_at"`
	CreatedAt time.Time  `db:"created_at"`
}

// TodoError is every way a command can fail.
type TodoError interface {
	error
	isTodoError()
}

type NotFound struct{ ID int64 }

func (NotFound) isTodoError() {}

func (e NotFound) Error() string { return fmt.Sprintf("no todo #%v", e.ID) }

type Invalid struct{ Reason string }

func (Invalid) isTodoError() {}

func (e Invalid) Error() string { return fmt.Sprintf("%v", e.Reason) }

type Usage struct{ Cause error }

func (Usage) isTodoError() {}

func (e Usage) Error() string { return fmt.Sprintf("%v", e.Cause) }

func (e Usage) Unwrap() error { return e.Cause }

type Storage struct{ Cause error }

func (Storage) isTodoError() {}

func (e Storage) Error() string { return fmt.Sprintf("database error: %v", e.Cause) }

func (e Storage) Unwrap() error { return e.Cause }

// Overdue reports whether t is still open after its due date.
//
//line todo.ego:39
func (t Todo) Overdue(now time.Time) bool {
	return t.DoneAt == nil && t.Due != nil && t.Due.Before(now.Truncate(24*time.Hour))
}
