// Code generated by ego generate from checks.ego. DO NOT EDIT.

// Package checks exercises check, must, else and fail.
package checks

import (
	"errors"
	"fmt"
	"os"
	"strconv"
)

//line checks.ego:10
var ErrEmpty = errors.New("empty")

func parse(s string) (int, error) {
	if s == "" {
		return 0, ErrEmpty
	}
	return strconv.Atoi(s)
}

func Sum(a, b string) (int, error) {
	x, err := parse(a)
	if err != nil {
		return 0, fmt.Errorf("parse: %w", err)
	}
//line checks.ego:21
	y, err := parse(b)
	if err != nil {
		return 0, fmt.Errorf("parse second number %v: %w", b, err)
	}
//line checks.ego:22
	return x + y, nil
}

func Assign(s string) (n int, err error) {
	v, err2 := parse(s)
	if err2 != nil {
		return 0, fmt.Errorf("parse: %w", err2)
	}
	n = v
//line checks.ego:27
	return n, nil
}

func Touch(path string) error {
	if err := os.WriteFile(path, nil, 0o600); err != nil {
		return fmt.Errorf("os.WriteFile: %w", err)
	}
//line checks.ego:32
	return nil
}

func OrZero(s string) int {
	n, err := parse(s)
	if err != nil {
		n = 0
	}
//line checks.ego:37
	return n
}

func OrDefault(s string, def int) int {
	n := 1
	if v, err := parse(s); err != nil {
		n = def
	} else {
		n = v
	}
//line checks.ego:43
	return n
}

func MustParse(s string) int {
	n, err := strconv.Atoi(s)
	if err != nil {
		panic(err)
	}
//line checks.ego:48
	return n
}

func Positive(n int) (int, error) {
	if n < 0 {
		return 0, fmt.Errorf("negative: %v", n)
	}
	if n == 0 {
		return 0, errors.New("zero")
	}
	return n, nil
}
