// Code generated by ego generate from inpackage_test.ego. DO NOT EDIT.

package checks

import (
	"fmt"
	"testing"
)

// An in-package test in effect-go: it uses the unexported parse.
//
//line inpackage_test.ego:6
func TestInPackage(t *testing.T) {
	n, err := parse("41")
	if err != nil {
		panic(err)
	}
//line inpackage_test.ego:8
	var got string
	switch n + 1 {
	case 42:
		got = "ok"
	default:
		got = fmt.Sprintf("got %d", n+1)
	}
//line inpackage_test.ego:12
	if got != "ok" {
		t.Fatal(got)
	}
	v, err := parse("")
	if err != nil {
		v = -1
	}
//line inpackage_test.ego:16
	if v != -1 {
		t.Fatal(v)
	}
}
