// Code generated by ego generate from eject.ego. DO NOT EDIT.

package main

import (
	"bytes"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/effect-go/effect-go/internal/layers"
	"github.com/effect-go/effect-go/internal/lower"
)

// ejectCmd turns effect-go packages into plain Go for good: each x.ego
// becomes x.go, the Go it compiles to, without //line directives or the
// "generated" header, and the .ego files go. Wiring becomes layers.go, and
// the injector files go. The code still imports the runtime library.
// Without -w, it prints what it would do.
//
//line eject.ego:15
func ejectCmd(args []string) error {
	fl := flag.NewFlagSet("eject", flag.ExitOnError)
	write := fl.Bool("w", false, "eject: without -w, only print what would change")
	fl.Parse(args)
	dirs, err := egoDirs(fl.Args())
	if err != nil {
		return err
	}
//line eject.ego:25
	type step struct {
		path   string // file to write
		code   []byte
		remove []string
	}
	var steps []step
	im := lower.NewImporter()
	for _, dir := range dependencyOrder(dirs) {
		res, err := lower.Generate(lower.Config{Dir: dir, NoLines: true, Importer: im})
		if err != nil {
			return fmt.Errorf("%v: %w", rel(dir), err)
		}
//line eject.ego:34
		for _, d := range res.Diags {
			fmt.Fprintln(os.Stderr, rel(d.Pos.String())+": "+d.Msg)
		}
		if len(res.Diags) > 0 {
			return fmt.Errorf("%s doesn't compile: fix it before ejecting", rel(dir))
		}
		for _, out := range res.Outputs {
			// The generated file may not exist yet: ejecting doesn't need it.
			s := step{path: plainName(out.Go), code: dropHeader(out.Code), remove: []string{out.Ego}}
			if s.path != out.Go {
				s.remove = append(s.remove, out.Go)
			}
			steps = append(steps, s)
		}
		lr, err := layers.Generate(dir)
		if err != nil {
			return fmt.Errorf("%v: %w", rel(dir), err)
		}
//line eject.ego:49
		if lr != nil {
			if len(lr.Diags) > 0 {
				return fmt.Errorf("%s: the wiring doesn't compile: run ego generate", rel(dir))
			}
			code := bytes.Replace(dropHeader(lr.Code), []byte("//go:build !"+layers.Tag+"\n\n"), nil, 1)
			s := step{path: plainName(lr.Path), code: code, remove: layers.InjectorFiles(dir)}
			if s.path != lr.Path {
				s.remove = append(s.remove, lr.Path)
			}
			steps = append(steps, s)
		}
	}
	for _, s := range steps {
		fmt.Printf("write %s, remove %s\n", rel(s.path), strings.Join(relAll(s.remove), ", "))
	}
	if !*write {
		if len(steps) > 0 {
			fmt.Println("(nothing changed: run ego eject -w to do it)")
		}
		return nil
	}
	for _, s := range steps {
		if err := os.WriteFile(s.path, s.code, 0o666); err != nil {
			return err
		}
//line eject.ego:72
		for _, r := range s.remove {
			if err := os.Remove(r); err != nil && !os.IsNotExist(err) {
				return err
			}
		}
	}
	return nil
}

// plainName returns the name a generated file takes once ejected: x.go for
// x_ego.go, x_test.go for x_ego_test.go, layers.go for layers_ego.go. It
// keeps the generated name if the plain one is taken.
func plainName(gen string) string {
	dir, base := filepath.Split(gen)
	name := strings.Replace(base, "_ego", "", 1)
	if _, err := os.Stat(filepath.Join(dir, name)); err == nil {
		return gen
	}
	return filepath.Join(dir, name)
}

// dropHeader removes the "Code generated … DO NOT EDIT." line, so tools
// treat the file as written by hand.
func dropHeader(code []byte) []byte {
	first, rest, ok := bytes.Cut(code, []byte("\n"))
	if !ok || !bytes.HasPrefix(first, []byte("// Code generated by ego generate")) {
		return code
	}
	return bytes.TrimLeft(rest, "\n")
}

func relAll(paths []string) []string {
	var out []string
	for _, p := range paths {
		out = append(out, rel(p))
	}
	return out
}
