// Code generated by ego generate from fmt.ego. DO NOT EDIT.

package main

import (
	"bytes"
	"flag"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"strings"

	"github.com/effect-go/effect-go/internal/syntax/format"
)

//line fmt.ego:15
func fmtCmd(args []string) error {
	fl := flag.NewFlagSet("fmt", flag.ExitOnError)
	list := fl.Bool("l", false, "list files whose formatting differs")
	write := fl.Bool("w", false, "write the result to the file")
	fl.Parse(args)
	paths := fl.Args()
	if len(paths) == 0 {
		if !*list && !*write {
			// Like gofmt: format stdin to stdout.
			src, err := readAll(os.Stdin)
			if err != nil {
				return err
			}
//line fmt.ego:25
			out, err := format.Source(src)
			if err != nil {
				return err
			}
//line fmt.ego:26
			if _, err := os.Stdout.Write(out); err != nil {
				return err
			}
//line fmt.ego:27
			return nil
		}
		paths = []string{"."}
	}
	failed := false
	for _, root := range paths {
		root = strings.TrimSuffix(root, "/...")
		if err := filepath.WalkDir(root, func(path string, d fs.DirEntry, err error) error {
			if err != nil {
				return err
			}
//line fmt.ego:36
			if d.IsDir() {
				if path != root && (strings.HasPrefix(d.Name(), ".") || d.Name() == "vendor" || d.Name() == "testdata") {
					return filepath.SkipDir
				}
				return nil
			}
			if !strings.HasSuffix(path, ".ego") {
				return nil
			}
			src, err2 := os.ReadFile(path)
			if err2 != nil {
				return err2
			}
//line fmt.ego:46
			out, err := format.Source(src)
			if err != nil {
				fmt.Fprintf(os.Stderr, "%s:%v\n", path, err)
				failed = true
				return nil
			}
			if bytes.Equal(src, out) {
				return nil
			}
			if *list {
				fmt.Println(path)
			}
			if *write {
				return os.WriteFile(path, out, 0o666)
			}
			if !*list {
				os.Stdout.Write(out)
			}
			return nil
		}); err != nil {
			return err
		}
	}
//line fmt.ego:67
	if failed {
		return errSilent
	}
	return nil
}

func readAll(f *os.File) ([]byte, error) {
	var b bytes.Buffer
	_, err := b.ReadFrom(f)
	return b.Bytes(), err
}
