// Code generated by ego generate from lsp.ego. DO NOT EDIT.

package main

import (
	"flag"
	"io"
	"os"

	"github.com/effect-go/effect-go/internal/lsp"
)

//line lsp.ego:11
func lspCmd(args []string) error {
	fl := flag.NewFlagSet("lsp", flag.ExitOnError)
	gopls := fl.String("gopls", "gopls", "path to gopls")
	logFile := fl.String("log", "", "write a debug log to this file")
	fl.Parse(args)
	var log io.Writer
	if *logFile != "" {
		f, err := os.Create(*logFile)
		if err != nil {
			return err
		}
//line lsp.ego:19
		defer f.Close()
		log = f
	}
	return lsp.Run(lsp.Config{Gopls: *gopls, Log: log}, os.Stdin, os.Stdout)
}
