// Code generated by ego generate from main.ego. DO NOT EDIT.

// Command ego compiles and formats effect-go (.ego) files.
//
//	ego generate [-check] [packages] write the Go for each .ego file (default ./...)
//	ego fmt [-l] [-w] [paths] format .ego files (default: stdin to stdout; ./... with -l or -w)
//	ego test [args]           ego generate, then go test with the same arguments
//	ego vet [packages]        go vet, then the effect-go analyzers
//	ego eject [-w] [packages] turn the packages into plain Go, for good
//	ego new [-replace dir] module/path [dir] create a project
//	ego lsp                   run the language server proxy in front of gopls
//	ego version
package main

import (
	"fmt"
	"os"
	"runtime/debug"
)

// version is the release go install built ego from, or "devel".
//
//line main.ego:20
func version() string {
	if bi, ok := debug.ReadBuildInfo(); ok && bi.Main.Version != "" && bi.Main.Version != "(devel)" {
		return bi.Main.Version
	}
	return "devel"
}

func usage() {
	fmt.Fprint(os.Stderr, `ego compiles effect-go (.ego) files to Go.

Usage:
	ego generate [-check] [dirs]              generate x_ego.go for each x.ego, and layers_ego.go (default ./...)
	ego fmt [-l] [-w] [paths]                 format .ego files (default: stdin to stdout; ./... with -l or -w)
	ego test [go test flags] [packages]       ego generate, then go test with the same arguments
	ego vet [packages]                        go vet, then the effect-go analyzers
	ego eject [-w] [packages]                 turn .ego files into plain .go files for good (prints the plan without -w)
	ego new [-replace dir] module/path [dir]  create a project: a small HTTP service, with AGENTS.md
	ego lsp                                   language server: gopls with .ego support
	ego version
`)
	os.Exit(2)
}

func main() {
	if isVetTool(os.Args) {
		vetTool()
		return
	}
	if len(os.Args) < 2 {
		usage()
	}
	cmd, args := os.Args[1], os.Args[2:]
	var err error
	switch cmd {
	case "generate", "gen":
		err = generate(args)
	case "fmt":
		err = fmtCmd(args)
	case "test":
		err = testCmd(args)
	case "vet":
		err = vetCmd(args)
	case "new":
		err = newCmd(args)
	case "eject":
		err = ejectCmd(args)
	case "lsp":
		err = lspCmd(args)
	case "version":
		fmt.Println("ego", version())
	case "help", "-h", "--help":
		usage()
	default:
		fmt.Fprintf(os.Stderr, "ego: unknown command %q\n", cmd)
		usage()
	}
	if err != nil {
		if err != errSilent {
			fmt.Fprintln(os.Stderr, "ego:", err)
		}
		os.Exit(1)
	}
}

var errSilent = fmt.Errorf("failed")
