// Code generated by ego generate from new.ego. DO NOT EDIT.

package main

import (
	"bytes"
	"embed"
	"flag"
	"fmt"
	"io/fs"
	"os"
	"os/exec"
	"path"
	"path/filepath"
	"strings"
	"text/template"
)

//go:embed testdata/template
//line new.ego:18
var projectTemplate embed.FS

const modulePath = "github.com/effect-go/effect-go"

// newCmd creates a project: a small HTTP service in effect-go, with the
// language's one-page guide for people and agents.
func newCmd(args []string) error {
	fl := flag.NewFlagSet("new", flag.ExitOnError)
	replace := fl.String("replace", "", "use the effect-go checkout in this directory, through a replace directive")
	fl.Usage = func() {
		fmt.Fprintln(os.Stderr, "usage: ego new [-replace dir] module/path [dir]")
		fl.PrintDefaults()
	}
	fl.Parse(args)
	if fl.NArg() < 1 || fl.NArg() > 2 {
		fl.Usage()
		os.Exit(2)
	}
	module := fl.Arg(0)
	dir := path.Base(module)
	if fl.NArg() == 2 {
		dir = fl.Arg(1)
	}
	if entries, err := os.ReadDir(dir); err == nil && len(entries) > 0 {
		return fmt.Errorf("%s is not empty", dir)
	}
	if err := os.MkdirAll(dir, 0o777); err != nil {
		return err
	}
//line new.ego:45
	data := struct{ Module, Name string }{module, path.Base(module)}
	if err := fs.WalkDir(projectTemplate, "testdata/template", func(p string, d fs.DirEntry, err error) error {
		if err != nil || d.IsDir() {
			return err
		}
		src, err := projectTemplate.ReadFile(p)
		if err != nil {
			return err
		}
//line new.ego:51
		name := path.Base(p)
		if name == "gitattributes" {
			name = ".gitattributes" // embed skips dot files
		}
		if base, ok := strings.CutSuffix(name, ".tmpl"); ok {
			var b bytes.Buffer
			if err := template.Must(template.New(name).Parse(string(src))).Execute(&b, data); err != nil {
				return err
			}
//line new.ego:58
			name, src = base, b.Bytes()
		}
		return os.WriteFile(filepath.Join(dir, name), src, 0o666)
	}); err != nil {
		return err
	}
//line new.ego:62
	self, err := os.Executable()
	if err != nil {
		return err
	}
//line new.ego:63
	steps := [][]string{{"go", "mod", "init", module}}
	// The generated code imports the runtime packages: get them first.
	// Tidy after generating: until then, only .ego files import packages,
	// and go mod tidy can't see them.
	get := []string{"go", "get"}
	for _, pkg := range []string{"scope", "schedule", "trace", "layer"} {
		get = append(get, modulePath+"/"+pkg+"@latest")
	}
	if *replace != "" {
		abs, err := filepath.Abs(*replace)
		if err != nil {
			return err
		}
//line new.ego:73
		steps = append(steps, []string{"go", "mod", "edit", "-require=" + modulePath + "@v0.0.0", "-replace=" + modulePath + "=" + abs})
		for i := 2; i < len(get); i++ {
			get[i] = strings.TrimSuffix(get[i], "@latest")
		}
	}
	steps = append(steps, get, []string{self, "generate", "./..."}, []string{"go", "mod", "tidy"})
	for _, s := range steps {
		cmd := exec.Command(s[0], s[1:]...)
		cmd.Dir, cmd.Stdout, cmd.Stderr = dir, os.Stdout, os.Stderr
		if err := cmd.Run(); err != nil {
			return fmt.Errorf("%v: %w", cmd, err)
		}
	}
//line new.ego:84
	fmt.Printf("\ncreated %s. Next:\n\tcd %s && ego test ./... && go run .\n", dir, dir)
	return nil
}
