package main

import (
	"os"
	"os/exec"
	"os/signal"
	"regexp"
	"strings"

	"github.com/effect-go/effect-go/internal/lower"
)

// testCmd regenerates the packages to test, then runs go test with the same
// arguments, so tests never run against stale generated code.
func testCmd(args []string) error {
	var pkgs []string
	for _, a := range args {
		if a == "." || a == ".." || strings.HasPrefix(a, "./") || strings.HasPrefix(a, "../") || strings.HasPrefix(a, "/") {
			pkgs = append(pkgs, a)
		}
	}
	if len(pkgs) == 0 {
		pkgs = []string{"."}
	}
	if err := generate(pkgs); err != nil {
		return err
	}
	if wantsCoverage(args) {
		restore, err := withoutLines(pkgs)
		defer restore()
		if err != nil {
			return err
		}
		// Ctrl-C stops go test; the files are restored once it returns.
		signal.Ignore(os.Interrupt)
		defer signal.Reset(os.Interrupt)
	}
	cmd := exec.Command("go", append([]string{"test"}, args...)...)
	cmd.Stdin, cmd.Stdout, cmd.Stderr = os.Stdin, os.Stdout, os.Stderr
	if err := cmd.Run(); err != nil {
		return errSilent
	}
	return nil
}

func wantsCoverage(args []string) bool {
	for _, a := range args {
		if a == "-cover" || strings.HasPrefix(a, "-cover=") || strings.HasPrefix(a, "-coverprofile") || strings.HasPrefix(a, "-coverpkg") || strings.HasPrefix(a, "-covermode") {
			return true
		}
	}
	return false
}

var genFrom = regexp.MustCompile(`(?m)^(// Code generated by ego generate) from [^ ]+\.ego(\. DO NOT EDIT\.)$`)

// withoutLines rewrites the generated files for a coverage run, and returns
// a function that puts the committed files back. As committed, they lead
// coverage to report garbled .ego positions that go tool cover can't read
// (golang/go#41222); rewritten without //line directives and without the
// source in their header, coverage reports the generated Go, which every
// coverage tool reads. (go test -overlay would avoid touching the files,
// but coverage ignores overlays.)
func withoutLines(pkgs []string) (restore func(), err error) {
	saved := map[string][]byte{}
	restore = func() {
		for path, code := range saved {
			os.WriteFile(path, code, 0o666)
		}
	}
	dirs, err := egoDirs(pkgs)
	if err != nil {
		return restore, err
	}
	im := lower.NewImporter()
	for _, dir := range dependencyOrder(dirs) {
		res, err := lower.Generate(lower.Config{Dir: dir, NoLines: true, Importer: im})
		if err != nil {
			return restore, err
		}
		for _, out := range res.Outputs {
			old, err := os.ReadFile(out.Go)
			if err != nil {
				return restore, err
			}
			saved[out.Go] = old
			// The header names the .ego file, and coverage attributes the
			// file to it too: keep "Code generated … DO NOT EDIT" only.
			code := genFrom.ReplaceAll(out.Code, []byte("$1$2"))
			if err := os.WriteFile(out.Go, code, 0o666); err != nil {
				return restore, err
			}
		}
	}
	return restore, nil
}
