// Code generated by ego generate from test.ego. DO NOT EDIT.

package main

import (
	"fmt"
	"os"
	"os/exec"
	"os/signal"
	"path/filepath"
	"regexp"
	"strings"

	"github.com/effect-go/effect-go/internal/lower"
)

// testCmd regenerates the packages to test, then runs go test with the same
// arguments, so tests never run against stale generated code.
//
//line test.ego:17
func testCmd(args []string) error {
	pkgs, err := testPackages(args)
	if err != nil {
		return err
	}
//line test.ego:19
	if err := generate(pkgs); err != nil {
		return err
	}
//line test.ego:20
	if wantsCoverage(args) {
		restore, err := withoutLines(pkgs)
		defer restore()
		if err != nil {
			return err
		}
		// Ctrl-C stops go test; the files are restored once it returns.
		signal.Ignore(os.Interrupt)
		defer signal.Reset(os.Interrupt)
	}
	cmd := exec.Command("go", append([]string{"test"}, args...)...)
	cmd.Stdin, cmd.Stdout, cmd.Stderr = os.Stdin, os.Stdout, os.Stderr
	if err := cmd.Run(); err != nil {
		return errSilent
	}
	return nil
}

// boolFlags are go test's and go build's flags that take no value: any
// other flag written without = takes the next argument.
var boolFlags = map[string]bool{
	"a": true, "asan": true, "benchmem": true, "cover": true, "failfast": true, "fullpath": true,
	"json": true, "linkshared": true, "modcacherw": true, "msan": true, "n": true, "race": true,
	"short": true, "trimpath": true, "v": true, "work": true, "x": true,
}

// testPackages returns the directories of the packages go test would test
// with args: patterns such as ./... as they are, import paths through go
// list. Flag values and what follows -args are not packages.
func testPackages(args []string) ([]string, error) {
	var local, paths []string
	for i := 0; i < len(args); i++ {
		a := args[i]
		if a == "-args" || a == "--args" {
			break
		}
		if strings.HasPrefix(a, "-") {
			if name := strings.TrimLeft(a, "-"); !strings.Contains(name, "=") && !boolFlags[name] {
				i++ // the flag's value
			}
			continue
		}
		if a == "." || a == ".." || strings.HasPrefix(a, "./") || strings.HasPrefix(a, "../") || filepath.IsAbs(a) {
			local = append(local, a)
		} else {
			paths = append(paths, a)
		}
	}
	if len(paths) > 0 {
		out, err := exec.Command("go", append([]string{"list", "-e", "-f", "{{.Dir}}"}, paths...)...).Output()
		if err != nil {
			return nil, fmt.Errorf("go list: %v", err)
		}
		local = append(local, strings.Fields(string(out))...)
	}
	if len(local) == 0 {
		local = []string{"."}
	}
	return local, nil
}

func wantsCoverage(args []string) bool {
	for _, a := range args {
		if a == "-cover" || strings.HasPrefix(a, "-cover=") || strings.HasPrefix(a, "-coverprofile") || strings.HasPrefix(a, "-coverpkg") || strings.HasPrefix(a, "-covermode") {
			return true
		}
	}
	return false
}

var genFrom = regexp.MustCompile(`(?m)^(// Code generated by ego generate) from [^ ]+\.ego(\. DO NOT EDIT\.)$`)

// withoutLines rewrites the generated files for a coverage run, and returns
// a function that puts the committed files back. As committed, they lead
// coverage to report garbled .ego positions that go tool cover can't read
// (golang/go#41222); rewritten without //line directives and without the
// source in their header, coverage reports the generated Go, which every
// coverage tool reads. (go test -overlay would avoid touching the files,
// but coverage ignores overlays.)
func withoutLines(pkgs []string) (restore func(), err error) {
	saved := map[string][]byte{}
	restore = func() {
		for path, code := range saved {
			os.WriteFile(path, code, 0o666)
		}
	}
	dirs, err := egoDirs(pkgs)
	if err != nil {
		return restore, err
	}
	im := lower.NewImporter()
	for _, dir := range dependencyOrder(dirs) {
		res, err := lower.Generate(lower.Config{Dir: dir, NoLines: true, Importer: im})
		if err != nil {
			return restore, err
		}
		for _, out := range res.Outputs {
			old, err := os.ReadFile(out.Go)
			if err != nil {
				return restore, err
			}
			saved[out.Go] = old
			// The header names the .ego file, and coverage attributes the
			// file to it too: keep "Code generated … DO NOT EDIT" only.
			code := genFrom.ReplaceAll(out.Code, []byte("$1$2"))
			if err := os.WriteFile(out.Go, code, 0o666); err != nil {
				return restore, err
			}
		}
	}
	return restore, nil
}
