// Code generated by ego generate from disk.ego. DO NOT EDIT.

// Package disk has an error set whose cases have no fields, and nothing
// else: no message needs fmt, so the generated Go mustn't import it.
package disk

// Disk is the error set Full | Gone.
//
//line disk.ego:5
type Disk interface {
	error
	isDisk()
}

type Full struct{}

func (Full) isDisk() {}

func (e Full) Error() string { return "disk 100% full" }

// As lets pointers to Full match as Full.
func (e Full) As(target any) bool {
	if t, ok := target.(*Full); ok {
		*t = e
		return true
	}
	return false
}

type Gone struct{}

func (Gone) isDisk() {}

func (e Gone) Error() string { return "gone" }

// As lets pointers to Gone match as Gone.
func (e Gone) As(target any) bool {
	if t, ok := target.(*Gone); ok {
		*t = e
		return true
	}
	return false
}
