// Code generated by ego generate from shapes.ego. DO NOT EDIT.

// Package shapes has enums: with data (a sum type) and without (constants).
package shapes

import (
	"math"
	"strconv"
)

// Shape is the enum Circle | Rect | Dot.
//
//line shapes.ego:6
type Shape interface {
	isShape()
}

type Circle struct{ R float64 }

func (Circle) isShape() {}

type Rect struct{ W, H float64 }

func (Rect) isShape() {}

type Dot struct{}

func (Dot) isShape() {}

//line shapes.ego:12
func Area(s Shape) float64 {
	var v float64
	if c, ok := s.(Circle); ok {
		v = math.Pi * c.R * c.R
	} else if r, ok := s.(Rect); ok {
		v = r.W * r.H
	} else if _, ok := s.(Dot); ok {
		v = 0
	} else {
		panic(s)
	}
	return v
}

// Color is the enum Red | Green | Blue.
//
//line shapes.ego:20
type Color int

const (
	Red Color = iota
	Green
	Blue
)

func (v Color) String() string {
	switch v {
	case Red:
		return "Red"
	case Green:
		return "Green"
	case Blue:
		return "Blue"
	}
	return "Color(" + strconv.Itoa(int(v)) + ")"
}

//line shapes.ego:26
func Warm(c Color) bool {
	var v bool
	switch c {
	case Red:
		v = true
	case Green, Blue:
		v = false
	default:
		panic(c)
	}
	return v
}

//line shapes.ego:33
type Level int

const (
	Low Level = iota
	High
)

func Name(l Level) string {
	switch l {
	case Low:
//line shapes.ego:42
		return "low"
	case High:
//line shapes.ego:43
		return "high"
	}
	return "?"
}
