// Code generated by ego generate from counts.ego. DO NOT EDIT.

package multi

import (
	"context"
	"fmt"
	"strings"
	"sync"

	"github.com/effect-go/effect-go/trace"
)

// Count stores the length of each word, in parallel, and returns how many
// distinct words there were.
//
//line counts.ego:8
func Count(ctx context.Context, s *Store[string, int], text string) (_ int, err error) {
	ctx, span := trace.Start(ctx, "multi.Count")
	defer trace.End(span, &err)
//line counts.ego:11
	words := strings.Fields(text)
	errs := make(chan error, len(words))
	var wg sync.WaitGroup
	for _, w := range words {
		wg.Go(func() {
			errs <- s.Put(ctx, w, len(w)) // ctx flows into the goroutine
		})
	}
	wg.Wait()
	close(errs)
	for err := range errs {
		if err != nil {
			return 0, err
		}
	}
//line counts.ego:24
	return s.Size(ctx), nil
}

// Lookup returns a word's length, or -1.
func Lookup(ctx context.Context, s *Store[string, int], w string) (_ int, err error) {
	ctx, span := trace.Start(ctx, "multi.Lookup")
	defer trace.End(span, &err)
//line counts.ego:29
	n, ok, err := s.Get(ctx, w)
	if err != nil {
		return 0, fmt.Errorf("s.Get: %w", err)
	}
//line counts.ego:30
	var v int
	if ok {
		v = n
	} else {
		v = -1
	}
	return v, nil
}
