// Code generated by ego generate from store.ego. DO NOT EDIT.

// Package multi has two .ego files that use each other, generics, and an
// effect function without an error.
package multi

import (
	"context"
	"sync"

	"github.com/effect-go/effect-go/trace"
)

//line store.ego:7
type Store[K comparable, V any] struct {
	mu sync.Mutex
	m  map[K]V
}

func NewStore[K comparable, V any]() *Store[K, V] { return &Store[K, V]{m: map[K]V{}} }

func (s *Store[K, V]) Get(ctx context.Context, k K) (_ V, _ bool, err error) {
	ctx, span := trace.Start(ctx, "Store.Get")
	defer trace.End(span, &err)
	s.mu.Lock()
	defer s.mu.Unlock()
	v, ok := s.m[k]
	return v, ok, ctx.Err()
}

//line store.ego:21
func (s *Store[K, V]) Put(ctx context.Context, k K, v V) (err error) {
	ctx, span := trace.Start(ctx, "Store.Put")
	defer trace.End(span, &err)
	s.mu.Lock()
	defer s.mu.Unlock()
	s.m[k] = v
	return nil
}

// Size has no error result: it still gets ctx and a span.
//
//line store.ego:28
func (s *Store[K, V]) Size(ctx context.Context) (_ int) {
	ctx, span := trace.Start(ctx, "Store.Size")
	defer trace.End(span, nil)
	s.mu.Lock()
	defer s.mu.Unlock()
	return len(s.m)
}
